/** Copy for the "set or reset a password" flow. */
export const resetCopy = {
  en: {
    forgot: "Set or reset my password",
    sending: "Sending…",
    sent: "Check your inbox — we've sent you a link to set a new password.",
    needsEmail: "Enter your email address above first.",
    eyebrow: "Your account",
    heading: "Choose a new password",
    intro: "Pick a password you'll remember. You'll stay signed in afterwards.",
    label: "New password",
    placeholder: "At least 8 characters",
    save: "Save password",
    saving: "Saving…",
    done: "Your password is saved. You can sign in with it from now on.",
    invalid: "This link has expired. Ask for a new one from the sign-in page.",
    error: "Something went wrong. Please try again.",
    backToAccount: "Go to my account",
  },
  no: {
    forgot: "Lag eller bytt passord",
    sending: "Sender…",
    sent: "Sjekk innboksen — vi har sendt deg en lenke for å lage nytt passord.",
    needsEmail: "Skriv e-postadressen din over først.",
    eyebrow: "Kontoen din",
    heading: "Velg et nytt passord",
    intro: "Velg et passord du husker. Du blir værende innlogget etterpå.",
    label: "Nytt passord",
    placeholder: "Minst 8 tegn",
    save: "Lagre passord",
    saving: "Lagrer…",
    done: "Passordet er lagret. Nå kan du logge inn med det.",
    invalid: "Denne lenken har gått ut. Be om en ny fra innloggingssiden.",
    error: "Noe gikk galt. Prøv igjen.",
    backToAccount: "Gå til kontoen min",
  },
  pl: {
    forgot: "Ustaw lub zmień hasło",
    sending: "Wysyłanie…",
    sent: "Sprawdź skrzynkę — wysłaliśmy link do ustawienia nowego hasła.",
    needsEmail: "Najpierw wpisz swój adres e-mail powyżej.",
    eyebrow: "Twoje konto",
    heading: "Wybierz nowe hasło",
    intro: "Wybierz hasło, które zapamiętasz. Zostaniesz zalogowany.",
    label: "Nowe hasło",
    placeholder: "Co najmniej 8 znaków",
    save: "Zapisz hasło",
    saving: "Zapisywanie…",
    done: "Hasło zapisane. Od teraz możesz się nim logować.",
    invalid: "Ten link wygasł. Poproś o nowy na stronie logowania.",
    error: "Coś poszło nie tak. Spróbuj ponownie.",
    backToAccount: "Przejdź do konta",
  },
  dk: {
    forgot: "Lav eller skift adgangskode",
    sending: "Sender…",
    sent: "Tjek din indbakke — vi har sendt et link til en ny adgangskode.",
    needsEmail: "Skriv din e-mailadresse ovenfor først.",
    eyebrow: "Din konto",
    heading: "Vælg en ny adgangskode",
    intro: "Vælg en adgangskode, du kan huske. Du forbliver logget ind.",
    label: "Ny adgangskode",
    placeholder: "Mindst 8 tegn",
    save: "Gem adgangskode",
    saving: "Gemmer…",
    done: "Adgangskoden er gemt. Nu kan du logge ind med den.",
    invalid: "Linket er udløbet. Bed om et nyt på login-siden.",
    error: "Noget gik galt. Prøv igen.",
    backToAccount: "Gå til min konto",
  },
  se: {
    forgot: "Skapa eller byt lösenord",
    sending: "Skickar…",
    sent: "Kolla inkorgen — vi har skickat en länk för nytt lösenord.",
    needsEmail: "Skriv din e-postadress ovanför först.",
    eyebrow: "Ditt konto",
    heading: "Välj ett nytt lösenord",
    intro: "Välj ett lösenord du kommer ihåg. Du förblir inloggad.",
    label: "Nytt lösenord",
    placeholder: "Minst 8 tecken",
    save: "Spara lösenord",
    saving: "Sparar…",
    done: "Lösenordet är sparat. Nu kan du logga in med det.",
    invalid: "Länken har gått ut. Be om en ny på inloggningssidan.",
    error: "Något gick fel. Försök igen.",
    backToAccount: "Gå till mitt konto",
  },
  fi: {
    forgot: "Luo tai vaihda salasana",
    sending: "Lähetetään…",
    sent: "Tarkista sähköpostisi — lähetimme linkin uuden salasanan luomiseen.",
    needsEmail: "Kirjoita ensin sähköpostiosoitteesi yllä.",
    eyebrow: "Tilisi",
    heading: "Valitse uusi salasana",
    intro: "Valitse salasana, jonka muistat. Pysyt kirjautuneena.",
    label: "Uusi salasana",
    placeholder: "Vähintään 8 merkkiä",
    save: "Tallenna salasana",
    saving: "Tallennetaan…",
    done: "Salasana tallennettu. Voit nyt kirjautua sillä.",
    invalid: "Linkki on vanhentunut. Pyydä uusi kirjautumissivulta.",
    error: "Jokin meni pieleen. Yritä uudelleen.",
    backToAccount: "Siirry tililleni",
  },
  de: {
    forgot: "Passwort festlegen oder ändern",
    sending: "Wird gesendet…",
    sent: "Sieh in dein Postfach — wir haben dir einen Link für ein neues Passwort geschickt.",
    needsEmail: "Trag oben zuerst deine E-Mail-Adresse ein.",
    eyebrow: "Dein Konto",
    heading: "Neues Passwort wählen",
    intro: "Wähle ein Passwort, das du dir merkst. Du bleibst danach angemeldet.",
    label: "Neues Passwort",
    placeholder: "Mindestens 8 Zeichen",
    save: "Passwort speichern",
    saving: "Wird gespeichert…",
    done: "Dein Passwort ist gespeichert. Ab jetzt kannst du dich damit anmelden.",
    invalid: "Dieser Link ist abgelaufen. Fordere auf der Anmeldeseite einen neuen an.",
    error: "Etwas ist schiefgelaufen. Bitte versuche es erneut.",
    backToAccount: "Zu meinem Konto",
  },
  fr: {
    forgot: "Créer ou changer mon mot de passe",
    sending: "Envoi…",
    sent: "Vérifiez votre boîte mail — nous vous avons envoyé un lien pour choisir un mot de passe.",
    needsEmail: "Entrez d'abord votre adresse e-mail ci-dessus.",
    eyebrow: "Votre compte",
    heading: "Choisissez un nouveau mot de passe",
    intro: "Choisissez un mot de passe dont vous vous souviendrez. Vous resterez connecté.",
    label: "Nouveau mot de passe",
    placeholder: "Au moins 8 caractères",
    save: "Enregistrer le mot de passe",
    saving: "Enregistrement…",
    done: "Mot de passe enregistré. Vous pouvez désormais l'utiliser pour vous connecter.",
    invalid: "Ce lien a expiré. Demandez-en un nouveau depuis la page de connexion.",
    error: "Une erreur s'est produite. Merci de réessayer.",
    backToAccount: "Aller à mon compte",
  },
  nl: {
    forgot: "Wachtwoord instellen of wijzigen",
    sending: "Versturen…",
    sent: "Check je inbox — we hebben je een link gestuurd voor een nieuw wachtwoord.",
    needsEmail: "Vul hierboven eerst je e-mailadres in.",
    eyebrow: "Je account",
    heading: "Kies een nieuw wachtwoord",
    intro: "Kies een wachtwoord dat je onthoudt. Je blijft daarna ingelogd.",
    label: "Nieuw wachtwoord",
    placeholder: "Minimaal 8 tekens",
    save: "Wachtwoord opslaan",
    saving: "Opslaan…",
    done: "Je wachtwoord is opgeslagen. Vanaf nu kun je hiermee inloggen.",
    invalid: "Deze link is verlopen. Vraag een nieuwe aan op de inlogpagina.",
    error: "Er ging iets mis. Probeer het opnieuw.",
    backToAccount: "Naar mijn account",
  },
} as const;
