/** Everything the places page says, in all nine languages. */
export type PlacesCopy = {
  tabs: { parks: string; walks: string; vets: string; stores: string };
  searchLabel: string;
  placeholder: string;
  search: string;
  useMyLocation: string;
  locating: string;
  geoDenied: string;
  searching: string;
  around: (place: string) => string;
  yourLocation: string;
  results: (count: number) => string;
  openNow: string;
  closedNow: string;
  hoursUnknown: string;
  away: (km: string) => string;
  ratings: (count: number) => string;
  noRating: string;
  verifiedPartner: string;
  emptyTitle: string;
  emptyBody: string;
  expand: (km: number) => string;
  widest: string;
  unavailable: string;
  notFound: string;
  busy: string;
  guidanceTitle: string;
  guidance: string[];
  mapLabel: string;
  directions: string;
};

export const placesCopy: Record<string, PlacesCopy> = {
  en: {
    tabs: { parks: "Dog parks", walks: "Scenic walks", vets: "Veterinarians", stores: "Pet stores" },
    searchLabel: "City, town or postcode",
    placeholder: "City, town or postcode",
    search: "Find places",
    useMyLocation: "Use my location",
    locating: "Finding you…",
    geoDenied: "We couldn't get your location. Type a place name instead — that works just as well.",
    searching: "Looking around…",
    around: (place) => `Around ${place}`,
    yourLocation: "Around you",
    results: (count) => (count === 1 ? "1 place" : `${count} places`),
    openNow: "Open now",
    closedNow: "Closed now",
    hoursUnknown: "Hours not listed",
    away: (km) => `${km} km away`,
    ratings: (count) => `${count} reviews`,
    noRating: "No reviews yet",
    verifiedPartner: "Verified Partner",
    emptyTitle: "Nothing close by just yet",
    emptyBody:
      "It's quiet around here, which often just means places aren't listed rather than that they don't exist. Try a wider search, or use the guidance below.",
    expand: (km) => `Search ${km} km instead`,
    widest: "That's as wide as we search.",
    unavailable: "The map service didn't answer just now. Please try again in a moment.",
    notFound: "We couldn't find that place. Try the nearest town.",
    busy: "A lot of searches at once — give it a moment and try again.",
    guidanceTitle: "Good to know wherever you walk",
    guidance: [
      "Lead rules change with the season. Most of Europe asks for a lead in spring, when birds nest on the ground.",
      "In forests and nature reserves, stay on the paths and keep your dog close — livestock and wildlife come first.",
      "Pick up after your dog everywhere, and carry water on warm days; tarmac gets hot long before the air does.",
      "Register with a vet before you need one, and note your nearest out-of-hours clinic.",
    ],
    mapLabel: "Map of dog-friendly places nearby",
    directions: "Open in Maps",
  },
  no: {
    tabs: { parks: "Hundeparker", walks: "Fine turer", vets: "Veterinærer", stores: "Dyrebutikker" },
    searchLabel: "By, sted eller postnummer",
    placeholder: "By, sted eller postnummer",
    search: "Finn steder",
    useMyLocation: "Bruk min posisjon",
    locating: "Finner deg…",
    geoDenied: "Vi fikk ikke posisjonen din. Skriv inn et stedsnavn i stedet — det fungerer like fint.",
    searching: "Ser oss rundt…",
    around: (place) => `Rundt ${place}`,
    yourLocation: "Rundt deg",
    results: (count) => (count === 1 ? "1 sted" : `${count} steder`),
    openNow: "Åpent nå",
    closedNow: "Stengt nå",
    hoursUnknown: "Åpningstider mangler",
    away: (km) => `${km} km unna`,
    ratings: (count) => `${count} vurderinger`,
    noRating: "Ingen vurderinger ennå",
    verifiedPartner: "Verifisert partner",
    emptyTitle: "Ingenting i nærheten akkurat nå",
    emptyBody:
      "Det er stille her, og som oftest betyr det bare at stedene ikke er registrert — ikke at de ikke finnes. Prøv et større område, eller les rådene under.",
    expand: (km) => `Søk ${km} km i stedet`,
    widest: "Så bredt søker vi.",
    unavailable: "Karttjenesten svarte ikke nå. Prøv igjen om et øyeblikk.",
    notFound: "Vi fant ikke stedet. Prøv nærmeste by.",
    busy: "Mange søk på én gang — vent litt og prøv igjen.",
    guidanceTitle: "Greit å vite uansett hvor du går",
    guidance: [
      "Båndtvangen følger årstidene. Store deler av Europa krever bånd om våren, når fugler hekker på bakken.",
      "I skog og verneområder: hold deg på stiene og hunden nær deg — beitedyr og vilt går først.",
      "Plukk opp etter hunden overalt, og ta med vann på varme dager; asfalten blir varm lenge før lufta gjør det.",
      "Registrer deg hos en veterinær før du trenger det, og noter nærmeste vaktklinikk.",
    ],
    mapLabel: "Kart over hundevennlige steder i nærheten",
    directions: "Åpne i Maps",
  },
  pl: {
    tabs: { parks: "Wybiegi dla psów", walks: "Ładne spacery", vets: "Weterynarze", stores: "Sklepy zoologiczne" },
    searchLabel: "Miasto, miejscowość lub kod pocztowy",
    placeholder: "Miasto, miejscowość lub kod pocztowy",
    search: "Znajdź miejsca",
    useMyLocation: "Użyj mojej lokalizacji",
    locating: "Szukamy Ciebie…",
    geoDenied: "Nie udało się ustalić lokalizacji. Wpisz nazwę miejsca — zadziała tak samo dobrze.",
    searching: "Rozglądamy się…",
    around: (place) => `W okolicy: ${place}`,
    yourLocation: "W Twojej okolicy",
    results: (count) => (count === 1 ? "1 miejsce" : `${count} miejsc`),
    openNow: "Otwarte teraz",
    closedNow: "Teraz zamknięte",
    hoursUnknown: "Brak godzin otwarcia",
    away: (km) => `${km} km stąd`,
    ratings: (count) => `${count} opinii`,
    noRating: "Brak opinii",
    verifiedPartner: "Zweryfikowany partner",
    emptyTitle: "Na razie nic w pobliżu",
    emptyBody:
      "Tu jest spokojnie, a to zwykle znaczy tylko tyle, że miejsca nie są zgłoszone — nie że ich nie ma. Spróbuj większego promienia albo zajrzyj do wskazówek poniżej.",
    expand: (km) => `Szukaj w promieniu ${km} km`,
    widest: "Szerzej już nie szukamy.",
    unavailable: "Usługa map nie odpowiedziała. Spróbuj ponownie za chwilę.",
    notFound: "Nie znaleźliśmy tego miejsca. Spróbuj najbliższego miasta.",
    busy: "Dużo zapytań naraz — poczekaj chwilę i spróbuj ponownie.",
    guidanceTitle: "Warto wiedzieć, gdziekolwiek spacerujesz",
    guidance: [
      "Zasady dotyczące smyczy zmieniają się z porą roku. Wiosną, gdy ptaki gniazdują na ziemi, w większości Europy obowiązuje smycz.",
      "W lasach i rezerwatach trzymaj się ścieżek, a psa blisko siebie — zwierzęta gospodarskie i dzikie mają pierwszeństwo.",
      "Zawsze sprzątaj po psie i zabieraj wodę w ciepłe dni; asfalt nagrzewa się znacznie szybciej niż powietrze.",
      "Zapisz się do weterynarza, zanim będzie potrzebny, i zanotuj najbliższą całodobową lecznicę.",
    ],
    mapLabel: "Mapa miejsc przyjaznych psom w okolicy",
    directions: "Otwórz w Mapach",
  },
  dk: {
    tabs: { parks: "Hundeparker", walks: "Gode gåture", vets: "Dyrlæger", stores: "Dyrehandler" },
    searchLabel: "By, sted eller postnummer",
    placeholder: "By, sted eller postnummer",
    search: "Find steder",
    useMyLocation: "Brug min placering",
    locating: "Finder dig…",
    geoDenied: "Vi kunne ikke finde din placering. Skriv et stednavn i stedet — det virker lige så godt.",
    searching: "Vi kigger os omkring…",
    around: (place) => `Omkring ${place}`,
    yourLocation: "Omkring dig",
    results: (count) => (count === 1 ? "1 sted" : `${count} steder`),
    openNow: "Åbent nu",
    closedNow: "Lukket nu",
    hoursUnknown: "Åbningstider mangler",
    away: (km) => `${km} km herfra`,
    ratings: (count) => `${count} anmeldelser`,
    noRating: "Ingen anmeldelser endnu",
    verifiedPartner: "Verificeret partner",
    emptyTitle: "Ikke noget i nærheden lige nu",
    emptyBody:
      "Der er stille her, og det betyder som regel bare, at stederne ikke er registreret — ikke at de ikke findes. Prøv et større område, eller læs rådene nedenfor.",
    expand: (km) => `Søg ${km} km i stedet`,
    widest: "Bredere søger vi ikke.",
    unavailable: "Karttjenesten svarede ikke lige nu. Prøv igen om et øjeblik.",
    notFound: "Vi kunne ikke finde stedet. Prøv den nærmeste by.",
    busy: "Mange søgninger på én gang — vent lidt og prøv igen.",
    guidanceTitle: "Godt at vide, uanset hvor du går",
    guidance: [
      "Snorereglerne følger årstiderne. Store dele af Europa kræver snor om foråret, når fugle ruger på jorden.",
      "I skove og naturreservater: bliv på stierne og hold hunden tæt på — husdyr og vildt kommer først.",
      "Saml altid op efter hunden, og tag vand med på varme dage; asfalten bliver varm længe før luften.",
      "Bliv tilmeldt en dyrlæge, før du får brug for det, og noter den nærmeste vagtklinik.",
    ],
    mapLabel: "Kort over hundevenlige steder i nærheden",
    directions: "Åbn i Maps",
  },
  se: {
    tabs: { parks: "Hundrastgårdar", walks: "Fina promenader", vets: "Veterinärer", stores: "Djuraffärer" },
    searchLabel: "Stad, ort eller postnummer",
    placeholder: "Stad, ort eller postnummer",
    search: "Hitta platser",
    useMyLocation: "Använd min plats",
    locating: "Letar efter dig…",
    geoDenied: "Vi kunde inte hämta din plats. Skriv ett ortsnamn i stället — det fungerar lika bra.",
    searching: "Vi tittar oss omkring…",
    around: (place) => `Runt ${place}`,
    yourLocation: "Runt dig",
    results: (count) => (count === 1 ? "1 plats" : `${count} platser`),
    openNow: "Öppet nu",
    closedNow: "Stängt nu",
    hoursUnknown: "Öppettider saknas",
    away: (km) => `${km} km bort`,
    ratings: (count) => `${count} omdömen`,
    noRating: "Inga omdömen än",
    verifiedPartner: "Verifierad partner",
    emptyTitle: "Inget i närheten just nu",
    emptyBody:
      "Det är lugnt här, vilket oftast bara betyder att ställena inte är registrerade — inte att de saknas. Prova ett större område, eller läs tipsen nedan.",
    expand: (km) => `Sök ${km} km i stället`,
    widest: "Bredare än så söker vi inte.",
    unavailable: "Karttjänsten svarade inte just nu. Försök igen om en stund.",
    notFound: "Vi hittade inte platsen. Prova närmaste stad.",
    busy: "Många sökningar på en gång — vänta lite och försök igen.",
    guidanceTitle: "Bra att veta var du än går",
    guidance: [
      "Koppelreglerna följer årstiderna. Stora delar av Europa kräver koppel på våren, när fåglar häckar på marken.",
      "I skog och naturreservat: håll dig på stigarna och hunden nära — betesdjur och vilt går först.",
      "Plocka alltid upp efter hunden och ta med vatten varma dagar; asfalten blir varm långt före luften.",
      "Skriv in dig hos en veterinär innan du behöver det, och notera närmaste jourklinik.",
    ],
    mapLabel: "Karta över hundvänliga platser i närheten",
    directions: "Öppna i Maps",
  },
  fi: {
    tabs: { parks: "Koirapuistot", walks: "Kauniit lenkit", vets: "Eläinlääkärit", stores: "Lemmikkikaupat" },
    searchLabel: "Kaupunki, kunta tai postinumero",
    placeholder: "Kaupunki, kunta tai postinumero",
    search: "Etsi paikkoja",
    useMyLocation: "Käytä sijaintiani",
    locating: "Etsitään sinua…",
    geoDenied: "Emme saaneet sijaintiasi. Kirjoita paikan nimi — se toimii aivan yhtä hyvin.",
    searching: "Katsellaan ympärille…",
    around: (place) => `Alueella ${place}`,
    yourLocation: "Lähelläsi",
    results: (count) => (count === 1 ? "1 paikka" : `${count} paikkaa`),
    openNow: "Auki nyt",
    closedNow: "Suljettu nyt",
    hoursUnknown: "Aukioloajat puuttuvat",
    away: (km) => `${km} km päässä`,
    ratings: (count) => `${count} arvostelua`,
    noRating: "Ei vielä arvosteluja",
    verifiedPartner: "Vahvistettu kumppani",
    emptyTitle: "Lähistöllä ei juuri nyt ole mitään",
    emptyBody:
      "Täällä on hiljaista, ja useimmiten se tarkoittaa vain, ettei paikkoja ole merkitty — ei sitä, ettei niitä ole. Kokeile laajempaa aluetta tai lue alla olevat vinkit.",
    expand: (km) => `Etsi ${km} km säteeltä`,
    widest: "Laajemmalta emme etsi.",
    unavailable: "Karttapalvelu ei vastannut juuri nyt. Yritä hetken kuluttua uudelleen.",
    notFound: "Emme löytäneet paikkaa. Kokeile lähintä kaupunkia.",
    busy: "Paljon hakuja kerralla — odota hetki ja yritä uudelleen.",
    guidanceTitle: "Hyvä tietää, missä ikinä kuljetkin",
    guidance: [
      "Kytkemissäännöt vaihtuvat vuodenajan mukaan. Suuressa osassa Eurooppaa kevät tarkoittaa kytkentäpakkoa, kun linnut pesivät maassa.",
      "Metsissä ja luonnonsuojelualueilla pysy poluilla ja pidä koira lähellä — kotieläimet ja riista menevät edelle.",
      "Kerää jätökset kaikkialla ja ota vettä mukaan lämpiminä päivinä; asfaltti kuumenee paljon ilmaa nopeammin.",
      "Rekisteröidy eläinlääkärille ennen kuin tarvitset, ja merkitse lähin päivystys ylös.",
    ],
    mapLabel: "Kartta koiraystävällisistä paikoista lähistöllä",
    directions: "Avaa Mapsissa",
  },
  de: {
    tabs: { parks: "Hundewiesen", walks: "Schöne Spaziergänge", vets: "Tierärzte", stores: "Tierbedarf" },
    searchLabel: "Stadt, Ort oder Postleitzahl",
    placeholder: "Stadt, Ort oder Postleitzahl",
    search: "Orte finden",
    useMyLocation: "Meinen Standort verwenden",
    locating: "Wir suchen dich…",
    geoDenied: "Wir konnten deinen Standort nicht ermitteln. Gib stattdessen einen Ort ein — das klappt genauso gut.",
    searching: "Wir schauen uns um…",
    around: (place) => `Rund um ${place}`,
    yourLocation: "In deiner Nähe",
    results: (count) => (count === 1 ? "1 Ort" : `${count} Orte`),
    openNow: "Jetzt geöffnet",
    closedNow: "Jetzt geschlossen",
    hoursUnknown: "Öffnungszeiten fehlen",
    away: (km) => `${km} km entfernt`,
    ratings: (count) => `${count} Bewertungen`,
    noRating: "Noch keine Bewertungen",
    verifiedPartner: "Geprüfter Partner",
    emptyTitle: "Gerade nichts in der Nähe",
    emptyBody:
      "Hier ist es ruhig, und das heißt meist nur, dass Orte nicht eingetragen sind — nicht, dass es keine gibt. Probier einen größeren Umkreis oder lies die Hinweise unten.",
    expand: (km) => `Stattdessen ${km} km suchen`,
    widest: "Weiter suchen wir nicht.",
    unavailable: "Der Kartendienst hat gerade nicht geantwortet. Bitte versuch es gleich noch einmal.",
    notFound: "Diesen Ort haben wir nicht gefunden. Versuch die nächste Stadt.",
    busy: "Viele Suchen auf einmal — warte kurz und versuch es erneut.",
    guidanceTitle: "Gut zu wissen, wo immer du unterwegs bist",
    guidance: [
      "Die Leinenpflicht richtet sich nach der Jahreszeit. In weiten Teilen Europas gilt sie im Frühling, wenn Vögel am Boden brüten.",
      "In Wäldern und Schutzgebieten auf den Wegen bleiben und den Hund nah bei dir halten — Weidetiere und Wild gehen vor.",
      "Überall aufsammeln und an warmen Tagen Wasser mitnehmen; Asphalt wird viel früher heiß als die Luft.",
      "Melde dich bei einer Tierarztpraxis an, bevor du sie brauchst, und notiere die nächste Notfallklinik.",
    ],
    mapLabel: "Karte mit hundefreundlichen Orten in der Nähe",
    directions: "In Maps öffnen",
  },
  fr: {
    tabs: { parks: "Parcs canins", walks: "Belles balades", vets: "Vétérinaires", stores: "Animaleries" },
    searchLabel: "Ville, commune ou code postal",
    placeholder: "Ville, commune ou code postal",
    search: "Trouver des lieux",
    useMyLocation: "Utiliser ma position",
    locating: "Nous vous localisons…",
    geoDenied: "Nous n'avons pas pu obtenir votre position. Saisissez un nom de lieu — cela marche tout aussi bien.",
    searching: "Nous regardons autour…",
    around: (place) => `Autour de ${place}`,
    yourLocation: "Autour de vous",
    results: (count) => (count === 1 ? "1 lieu" : `${count} lieux`),
    openNow: "Ouvert maintenant",
    closedNow: "Fermé maintenant",
    hoursUnknown: "Horaires non indiqués",
    away: (km) => `à ${km} km`,
    ratings: (count) => `${count} avis`,
    noRating: "Pas encore d'avis",
    verifiedPartner: "Partenaire vérifié",
    emptyTitle: "Rien à proximité pour l'instant",
    emptyBody:
      "C'est calme par ici, ce qui signifie souvent que les lieux ne sont pas référencés, pas qu'ils n'existent pas. Essayez un rayon plus large, ou lisez les conseils ci-dessous.",
    expand: (km) => `Chercher dans ${km} km`,
    widest: "Nous ne cherchons pas plus loin.",
    unavailable: "Le service de cartes n'a pas répondu. Réessayez dans un instant.",
    notFound: "Nous n'avons pas trouvé ce lieu. Essayez la ville la plus proche.",
    busy: "Beaucoup de recherches à la fois — patientez un instant et réessayez.",
    guidanceTitle: "Bon à savoir où que vous marchiez",
    guidance: [
      "Les règles de laisse suivent les saisons. Au printemps, quand les oiseaux nichent au sol, la laisse est demandée presque partout en Europe.",
      "En forêt et en réserve naturelle, restez sur les sentiers et gardez votre chien près de vous — le bétail et la faune passent d'abord.",
      "Ramassez partout et emportez de l'eau les jours chauds ; le bitume chauffe bien avant l'air.",
      "Inscrivez-vous chez un vétérinaire avant d'en avoir besoin, et notez la clinique d'urgence la plus proche.",
    ],
    mapLabel: "Carte des lieux qui accueillent les chiens à proximité",
    directions: "Ouvrir dans Maps",
  },
  nl: {
    tabs: { parks: "Hondenlosloopgebieden", walks: "Mooie wandelingen", vets: "Dierenartsen", stores: "Dierenwinkels" },
    searchLabel: "Stad, plaats of postcode",
    placeholder: "Stad, plaats of postcode",
    search: "Plekken zoeken",
    useMyLocation: "Mijn locatie gebruiken",
    locating: "We zoeken je…",
    geoDenied: "We konden je locatie niet ophalen. Typ een plaatsnaam — dat werkt net zo goed.",
    searching: "We kijken rond…",
    around: (place) => `Rond ${place}`,
    yourLocation: "Bij jou in de buurt",
    results: (count) => (count === 1 ? "1 plek" : `${count} plekken`),
    openNow: "Nu open",
    closedNow: "Nu gesloten",
    hoursUnknown: "Openingstijden onbekend",
    away: (km) => `${km} km hiervandaan`,
    ratings: (count) => `${count} beoordelingen`,
    noRating: "Nog geen beoordelingen",
    verifiedPartner: "Geverifieerde partner",
    emptyTitle: "Nu even niets in de buurt",
    emptyBody:
      "Het is hier rustig, en dat betekent meestal alleen dat plekken niet geregistreerd zijn — niet dat ze er niet zijn. Probeer een groter gebied, of lees de tips hieronder.",
    expand: (km) => `Zoek binnen ${km} km`,
    widest: "Verder zoeken we niet.",
    unavailable: "De kaartendienst gaf even geen antwoord. Probeer het zo nog eens.",
    notFound: "We konden die plek niet vinden. Probeer de dichtstbijzijnde stad.",
    busy: "Veel zoekopdrachten tegelijk — wacht even en probeer opnieuw.",
    guidanceTitle: "Goed om te weten, waar je ook loopt",
    guidance: [
      "Aanlijnregels wisselen met het seizoen. In het voorjaar, als vogels op de grond broeden, geldt bijna overal in Europa een aanlijnplicht.",
      "Blijf in bossen en natuurgebieden op de paden en houd je hond dichtbij — vee en wild gaan voor.",
      "Ruim overal op en neem water mee op warme dagen; asfalt wordt veel eerder heet dan de lucht.",
      "Schrijf je in bij een dierenarts voordat je er een nodig hebt, en noteer de dichtstbijzijnde spoedkliniek.",
    ],
    mapLabel: "Kaart met hondvriendelijke plekken in de buurt",
    directions: "Openen in Maps",
  },
};

export function getPlacesCopy(locale: string): PlacesCopy {
  return placesCopy[locale] ?? placesCopy["en"]!;
}
