/** Copy for sending a place to a phone or a car navigation system. */
export type SendCopy = {
  send: string;
  close: string;
  title: string;
  intro: string;
  scanTitle: string;
  scanBody: string;
  carTitle: string;
  carBody: string;
  coords: string;
  copy: string;
  copied: string;
  shareToPhone: string;
  save: string;
  saved: string;
  savedTitle: string;
  savedEmpty: string;
  remove: string;
  plusHint: string;
  plusLink: string;
};

const en: SendCopy = {
  send: "Send this place",
  close: "Close",
  title: "Take this place with you",
  intro: "Scan the code with a phone, or type the coordinates straight into the car.",
  scanTitle: "To a phone",
  scanBody: "Point a phone camera at the code and it opens the place in maps, ready to navigate.",
  carTitle: "To the car",
  carBody: "Most car navigation systems let you enter coordinates. Copy them and type them in.",
  coords: "Coordinates",
  copy: "Copy",
  copied: "Copied",
  shareToPhone: "Share link",
  save: "Save this place",
  saved: "Saved",
  savedTitle: "Your saved places",
  savedEmpty: "Nothing saved yet.",
  remove: "Remove",
  plusHint: "Saving places is part of DoggMatch+.",
  plusLink: "See what's included",
};

export const sendCopy: Record<string, SendCopy> = {
  en,
  no: {
    send: "Send dette stedet",
    close: "Lukk",
    title: "Ta stedet med deg",
    intro: "Skann koden med mobilen, eller skriv koordinatene rett inn i bilen.",
    scanTitle: "Til mobilen",
    scanBody: "Rett mobilkameraet mot koden, så åpnes stedet i kart, klart til å kjøre etter.",
    carTitle: "Til bilen",
    carBody: "De fleste navigasjonssystemer tar imot koordinater. Kopier dem og skriv dem inn.",
    coords: "Koordinater",
    copy: "Kopier",
    copied: "Kopiert",
    shareToPhone: "Del lenke",
    save: "Lagre stedet",
    saved: "Lagret",
    savedTitle: "Stedene dine",
    savedEmpty: "Ingenting lagret ennå.",
    remove: "Fjern",
    plusHint: "Å lagre steder hører til DoggMatch+.",
    plusLink: "Se hva som er med",
  },
  pl: {
    send: "Wyślij to miejsce",
    close: "Zamknij",
    title: "Zabierz to miejsce ze sobą",
    intro: "Zeskanuj kod telefonem albo wpisz współrzędne wprost do nawigacji w aucie.",
    scanTitle: "Na telefon",
    scanBody: "Skieruj aparat na kod — miejsce otworzy się w mapach, gotowe do nawigacji.",
    carTitle: "Do samochodu",
    carBody: "Większość nawigacji przyjmuje współrzędne. Skopiuj je i wpisz.",
    coords: "Współrzędne",
    copy: "Kopiuj",
    copied: "Skopiowano",
    shareToPhone: "Udostępnij link",
    save: "Zapisz to miejsce",
    saved: "Zapisano",
    savedTitle: "Twoje zapisane miejsca",
    savedEmpty: "Nic jeszcze nie zapisano.",
    remove: "Usuń",
    plusHint: "Zapisywanie miejsc należy do DoggMatch+.",
    plusLink: "Zobacz, co obejmuje",
  },
  dk: {
    send: "Send dette sted",
    close: "Luk",
    title: "Tag stedet med dig",
    intro: "Scan koden med mobilen, eller skriv koordinaterne direkte ind i bilen.",
    scanTitle: "Til mobilen",
    scanBody: "Hold mobilkameraet op mod koden, så åbner stedet i kort, klar til at køre efter.",
    carTitle: "Til bilen",
    carBody: "De fleste navigationssystemer tager imod koordinater. Kopiér dem, og tast dem ind.",
    coords: "Koordinater",
    copy: "Kopiér",
    copied: "Kopieret",
    shareToPhone: "Del link",
    save: "Gem stedet",
    saved: "Gemt",
    savedTitle: "Dine gemte steder",
    savedEmpty: "Der er ikke gemt noget endnu.",
    remove: "Fjern",
    plusHint: "At gemme steder hører til DoggMatch+.",
    plusLink: "Se hvad der er med",
  },
  se: {
    send: "Skicka den här platsen",
    close: "Stäng",
    title: "Ta med platsen",
    intro: "Skanna koden med mobilen, eller skriv koordinaterna direkt i bilen.",
    scanTitle: "Till mobilen",
    scanBody: "Rikta mobilkameran mot koden så öppnas platsen i kartan, redo att köra till.",
    carTitle: "Till bilen",
    carBody: "De flesta navigationssystem tar emot koordinater. Kopiera dem och skriv in dem.",
    coords: "Koordinater",
    copy: "Kopiera",
    copied: "Kopierat",
    shareToPhone: "Dela länk",
    save: "Spara platsen",
    saved: "Sparad",
    savedTitle: "Dina sparade platser",
    savedEmpty: "Inget sparat än.",
    remove: "Ta bort",
    plusHint: "Att spara platser ingår i DoggMatch+.",
    plusLink: "Se vad som ingår",
  },
  fi: {
    send: "Lähetä tämä paikka",
    close: "Sulje",
    title: "Ota paikka mukaasi",
    intro: "Skannaa koodi puhelimella tai näppäile koordinaatit suoraan auton navigaattoriin.",
    scanTitle: "Puhelimeen",
    scanBody: "Suuntaa puhelimen kamera koodiin, niin paikka avautuu karttaan valmiina ajo-ohjeisiin.",
    carTitle: "Autoon",
    carBody: "Useimpiin navigaattoreihin voi syöttää koordinaatit. Kopioi ne ja näppäile sisään.",
    coords: "Koordinaatit",
    copy: "Kopioi",
    copied: "Kopioitu",
    shareToPhone: "Jaa linkki",
    save: "Tallenna paikka",
    saved: "Tallennettu",
    savedTitle: "Tallentamasi paikat",
    savedEmpty: "Mitään ei ole vielä tallennettu.",
    remove: "Poista",
    plusHint: "Paikkojen tallennus kuuluu DoggMatch+:aan.",
    plusLink: "Katso mitä siihen sisältyy",
  },
  de: {
    send: "Diesen Ort senden",
    close: "Schließen",
    title: "Nimm den Ort mit",
    intro: "Scanne den Code mit dem Handy oder tippe die Koordinaten direkt ins Auto ein.",
    scanTitle: "Aufs Handy",
    scanBody: "Halte die Handykamera auf den Code — der Ort öffnet sich in der Karte, bereit zur Navigation.",
    carTitle: "Ins Auto",
    carBody: "Die meisten Navis nehmen Koordinaten an. Kopiere sie und gib sie ein.",
    coords: "Koordinaten",
    copy: "Kopieren",
    copied: "Kopiert",
    shareToPhone: "Link teilen",
    save: "Ort speichern",
    saved: "Gespeichert",
    savedTitle: "Deine gespeicherten Orte",
    savedEmpty: "Noch nichts gespeichert.",
    remove: "Entfernen",
    plusHint: "Orte zu speichern gehört zu DoggMatch+.",
    plusLink: "Sieh, was dabei ist",
  },
  fr: {
    send: "Envoyer ce lieu",
    close: "Fermer",
    title: "Emportez ce lieu avec vous",
    intro: "Scannez le code avec un téléphone, ou saisissez les coordonnées directement dans la voiture.",
    scanTitle: "Vers le téléphone",
    scanBody: "Pointez l'appareil photo vers le code : le lieu s'ouvre dans la carte, prêt à guider.",
    carTitle: "Vers la voiture",
    carBody: "La plupart des GPS acceptent les coordonnées. Copiez-les et saisissez-les.",
    coords: "Coordonnées",
    copy: "Copier",
    copied: "Copié",
    shareToPhone: "Partager le lien",
    save: "Enregistrer ce lieu",
    saved: "Enregistré",
    savedTitle: "Vos lieux enregistrés",
    savedEmpty: "Rien d'enregistré pour l'instant.",
    remove: "Retirer",
    plusHint: "Enregistrer des lieux fait partie de DoggMatch+.",
    plusLink: "Voir ce qui est inclus",
  },
  nl: {
    send: "Deze plek versturen",
    close: "Sluiten",
    title: "Neem de plek mee",
    intro: "Scan de code met je telefoon, of tik de coördinaten zo in de auto in.",
    scanTitle: "Naar de telefoon",
    scanBody: "Richt de camera op de code — de plek opent in de kaart, klaar om naartoe te rijden.",
    carTitle: "Naar de auto",
    carBody: "De meeste navigatiesystemen accepteren coördinaten. Kopieer ze en voer ze in.",
    coords: "Coördinaten",
    copy: "Kopiëren",
    copied: "Gekopieerd",
    shareToPhone: "Link delen",
    save: "Plek bewaren",
    saved: "Bewaard",
    savedTitle: "Je bewaarde plekken",
    savedEmpty: "Nog niets bewaard.",
    remove: "Verwijderen",
    plusHint: "Plekken bewaren hoort bij DoggMatch+.",
    plusLink: "Bekijk wat erbij zit",
  },
};

export function getSendCopy(locale: string): SendCopy {
  return sendCopy[locale] ?? en;
}
