/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LangChar125RouteImport } from './routes/{-$lang}'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125AboutRouteImport } from './routes/{-$lang}/about'
import { Route as Char123LangChar125AccountRouteImport } from './routes/{-$lang}/account'
import { Route as Char123LangChar125AuthRouteImport } from './routes/{-$lang}/auth'
import { Route as Char123LangChar125BestApartmentDogsRouteImport } from './routes/{-$lang}/best-apartment-dogs'
import { Route as Char123LangChar125BestDogBreedsForFamiliesRouteImport } from './routes/{-$lang}/best-dog-breeds-for-families'
import { Route as Char123LangChar125BestDogsForFirstTimeOwnersRouteImport } from './routes/{-$lang}/best-dogs-for-first-time-owners'
import { Route as Char123LangChar125BrochureRouteImport } from './routes/{-$lang}/brochure'
import { Route as Char123LangChar125CompareRouteImport } from './routes/{-$lang}/compare'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125DogLifeRouteImport } from './routes/{-$lang}/dog-life'
import { Route as Char123LangChar125DogsThatCanBeLeftAloneRouteImport } from './routes/{-$lang}/dogs-that-can-be-left-alone'
import { Route as Char123LangChar125FindMyDogRouteImport } from './routes/{-$lang}/find-my-dog'
import { Route as Char123LangChar125GetADogRouteImport } from './routes/{-$lang}/get-a-dog'
import { Route as Char123LangChar125GuidesRouteImport } from './routes/{-$lang}/guides'
import { Route as Char123LangChar125LowSheddingDogsRouteImport } from './routes/{-$lang}/low-shedding-dogs'
import { Route as Char123LangChar125MemberCardRouteImport } from './routes/{-$lang}/member-card'
import { Route as Char123LangChar125MostMismatchedBreedsRouteImport } from './routes/{-$lang}/most-mismatched-breeds'
import { Route as Char123LangChar125MyDogRouteImport } from './routes/{-$lang}/my-dog'
import { Route as Char123LangChar125PartnersRouteImport } from './routes/{-$lang}/partners'
import { Route as Char123LangChar125PlusRouteImport } from './routes/{-$lang}/plus'
import { Route as Char123LangChar125PrivacyRouteImport } from './routes/{-$lang}/privacy'
import { Route as Char123LangChar125SourcesRouteImport } from './routes/{-$lang}/sources'
import { Route as Char123LangChar125TermsRouteImport } from './routes/{-$lang}/terms'
import { Route as Char123LangChar125TrainRouteImport } from './routes/{-$lang}/train'
import { Route as Char123LangChar125TravelRouteImport } from './routes/{-$lang}/travel'
import { Route as Char123LangChar125WhatADogCostsRouteImport } from './routes/{-$lang}/what-a-dog-costs'
import { Route as Char123LangChar125BreedsIndexRouteImport } from './routes/{-$lang}/breeds.index'
import { Route as Char123LangChar125BreedsBreedIdRouteImport } from './routes/{-$lang}/breeds.$breedId'
import { Route as Char123LangChar125CanDogsEatIndexRouteImport } from './routes/{-$lang}/can-dogs-eat.index'
import { Route as Char123LangChar125CanDogsEatFoodIdRouteImport } from './routes/{-$lang}/can-dogs-eat.$foodId'
import { Route as Char123LangChar125CheckoutCanceledRouteImport } from './routes/{-$lang}/checkout.canceled'
import { Route as Char123LangChar125CheckoutSuccessRouteImport } from './routes/{-$lang}/checkout.success'
import { Route as Char123LangChar125GetADogIndexRouteImport } from './routes/{-$lang}/get-a-dog.index'
import { Route as Char123LangChar125GetADogChooseRouteImport } from './routes/{-$lang}/get-a-dog.choose'
import { Route as Char123LangChar125GetADogCostsRouteImport } from './routes/{-$lang}/get-a-dog.costs'
import { Route as Char123LangChar125GetADogPrepareRouteImport } from './routes/{-$lang}/get-a-dog.prepare'
import { Route as Char123LangChar125GetADogReadyRouteImport } from './routes/{-$lang}/get-a-dog.ready'
import { Route as Char123LangChar125GetADogWelcomeHomeRouteImport } from './routes/{-$lang}/get-a-dog.welcome-home'
import { Route as Char123LangChar125MyDogIndexRouteImport } from './routes/{-$lang}/my-dog.index'
import { Route as Char123LangChar125MyDogContactsRouteImport } from './routes/{-$lang}/my-dog.contacts'
import { Route as Char123LangChar125MyDogFoodRouteImport } from './routes/{-$lang}/my-dog.food'
import { Route as Char123LangChar125MyDogNutritionRouteImport } from './routes/{-$lang}/my-dog.nutrition'
import { Route as Char123LangChar125MyDogPackRouteImport } from './routes/{-$lang}/my-dog.pack'
import { Route as Char123LangChar125MyDogPreviewRouteImport } from './routes/{-$lang}/my-dog.preview'
import { Route as Char123LangChar125MyDogPrintRouteImport } from './routes/{-$lang}/my-dog.print'
import { Route as Char123LangChar125MyDogSetupRouteImport } from './routes/{-$lang}/my-dog.setup'
import { Route as Char123LangChar125MyDogVetRouteImport } from './routes/{-$lang}/my-dog.vet'
import { Route as Char123LangChar125MyDogWeekRouteImport } from './routes/{-$lang}/my-dog.week'
import { Route as Char123LangChar125MyDogWeightRouteImport } from './routes/{-$lang}/my-dog.weight'
import { Route as Char123LangChar125PartnersPortalRouteImport } from './routes/{-$lang}/partners.portal'
import { Route as Char123LangChar125TrainIndexRouteImport } from './routes/{-$lang}/train.index'
import { Route as Char123LangChar125TrainJourneyRouteImport } from './routes/{-$lang}/train.journey'
import { Route as Char123LangChar125TrainLibraryRouteImport } from './routes/{-$lang}/train.library'
import { Route as Char123LangChar125TrainSetupRouteImport } from './routes/{-$lang}/train.setup'
import { Route as Char123LangChar125TravelIndexRouteImport } from './routes/{-$lang}/travel.index'
import { Route as Char123LangChar125TravelAbroadRouteImport } from './routes/{-$lang}/travel.abroad'
import { Route as Char123LangChar125TravelCarRouteImport } from './routes/{-$lang}/travel.car'
import { Route as Char123LangChar125TravelOutdoorsRouteImport } from './routes/{-$lang}/travel.outdoors'
import { Route as Char123LangChar125VerifyMemberIdRouteImport } from './routes/{-$lang}/verify.$memberId'
import { Route as Char123LangChar125GetADogBreedBreedIdRouteImport } from './routes/{-$lang}/get-a-dog.breed.$breedId'
import { Route as Char123LangChar125MyDogCareTopicIdRouteImport } from './routes/{-$lang}/my-dog.care.$topicId'
import { Route as Char123LangChar125TrainLessonsLessonIdRouteImport } from './routes/{-$lang}/train.lessons.$lessonId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125Route = Char123LangChar125RouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125AboutRoute = Char123LangChar125AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125AccountRoute =
  Char123LangChar125AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125AuthRoute = Char123LangChar125AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125BestApartmentDogsRoute =
  Char123LangChar125BestApartmentDogsRouteImport.update({
    id: '/best-apartment-dogs',
    path: '/best-apartment-dogs',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125BestDogBreedsForFamiliesRoute =
  Char123LangChar125BestDogBreedsForFamiliesRouteImport.update({
    id: '/best-dog-breeds-for-families',
    path: '/best-dog-breeds-for-families',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125BestDogsForFirstTimeOwnersRoute =
  Char123LangChar125BestDogsForFirstTimeOwnersRouteImport.update({
    id: '/best-dogs-for-first-time-owners',
    path: '/best-dogs-for-first-time-owners',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125BrochureRoute =
  Char123LangChar125BrochureRouteImport.update({
    id: '/brochure',
    path: '/brochure',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CompareRoute =
  Char123LangChar125CompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125DogLifeRoute =
  Char123LangChar125DogLifeRouteImport.update({
    id: '/dog-life',
    path: '/dog-life',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125DogsThatCanBeLeftAloneRoute =
  Char123LangChar125DogsThatCanBeLeftAloneRouteImport.update({
    id: '/dogs-that-can-be-left-alone',
    path: '/dogs-that-can-be-left-alone',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125FindMyDogRoute =
  Char123LangChar125FindMyDogRouteImport.update({
    id: '/find-my-dog',
    path: '/find-my-dog',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125GetADogRoute =
  Char123LangChar125GetADogRouteImport.update({
    id: '/get-a-dog',
    path: '/get-a-dog',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125GuidesRoute =
  Char123LangChar125GuidesRouteImport.update({
    id: '/guides',
    path: '/guides',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125LowSheddingDogsRoute =
  Char123LangChar125LowSheddingDogsRouteImport.update({
    id: '/low-shedding-dogs',
    path: '/low-shedding-dogs',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125MemberCardRoute =
  Char123LangChar125MemberCardRouteImport.update({
    id: '/member-card',
    path: '/member-card',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125MostMismatchedBreedsRoute =
  Char123LangChar125MostMismatchedBreedsRouteImport.update({
    id: '/most-mismatched-breeds',
    path: '/most-mismatched-breeds',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125MyDogRoute = Char123LangChar125MyDogRouteImport.update({
  id: '/my-dog',
  path: '/my-dog',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125PartnersRoute =
  Char123LangChar125PartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125PlusRoute = Char123LangChar125PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125PrivacyRoute =
  Char123LangChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125SourcesRoute =
  Char123LangChar125SourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125TermsRoute = Char123LangChar125TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125TrainRoute = Char123LangChar125TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125TravelRoute =
  Char123LangChar125TravelRouteImport.update({
    id: '/travel',
    path: '/travel',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125WhatADogCostsRoute =
  Char123LangChar125WhatADogCostsRouteImport.update({
    id: '/what-a-dog-costs',
    path: '/what-a-dog-costs',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125BreedsIndexRoute =
  Char123LangChar125BreedsIndexRouteImport.update({
    id: '/breeds/',
    path: '/breeds/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125BreedsBreedIdRoute =
  Char123LangChar125BreedsBreedIdRouteImport.update({
    id: '/breeds/$breedId',
    path: '/breeds/$breedId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CanDogsEatIndexRoute =
  Char123LangChar125CanDogsEatIndexRouteImport.update({
    id: '/can-dogs-eat/',
    path: '/can-dogs-eat/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CanDogsEatFoodIdRoute =
  Char123LangChar125CanDogsEatFoodIdRouteImport.update({
    id: '/can-dogs-eat/$foodId',
    path: '/can-dogs-eat/$foodId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CheckoutCanceledRoute =
  Char123LangChar125CheckoutCanceledRouteImport.update({
    id: '/checkout/canceled',
    path: '/checkout/canceled',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CheckoutSuccessRoute =
  Char123LangChar125CheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125GetADogIndexRoute =
  Char123LangChar125GetADogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125GetADogChooseRoute =
  Char123LangChar125GetADogChooseRouteImport.update({
    id: '/choose',
    path: '/choose',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125GetADogCostsRoute =
  Char123LangChar125GetADogCostsRouteImport.update({
    id: '/costs',
    path: '/costs',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125GetADogPrepareRoute =
  Char123LangChar125GetADogPrepareRouteImport.update({
    id: '/prepare',
    path: '/prepare',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125GetADogReadyRoute =
  Char123LangChar125GetADogReadyRouteImport.update({
    id: '/ready',
    path: '/ready',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125GetADogWelcomeHomeRoute =
  Char123LangChar125GetADogWelcomeHomeRouteImport.update({
    id: '/welcome-home',
    path: '/welcome-home',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125MyDogIndexRoute =
  Char123LangChar125MyDogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogContactsRoute =
  Char123LangChar125MyDogContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogFoodRoute =
  Char123LangChar125MyDogFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogNutritionRoute =
  Char123LangChar125MyDogNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogPackRoute =
  Char123LangChar125MyDogPackRouteImport.update({
    id: '/pack',
    path: '/pack',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogPreviewRoute =
  Char123LangChar125MyDogPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogPrintRoute =
  Char123LangChar125MyDogPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogSetupRoute =
  Char123LangChar125MyDogSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogVetRoute =
  Char123LangChar125MyDogVetRouteImport.update({
    id: '/vet',
    path: '/vet',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogWeekRoute =
  Char123LangChar125MyDogWeekRouteImport.update({
    id: '/week',
    path: '/week',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125MyDogWeightRoute =
  Char123LangChar125MyDogWeightRouteImport.update({
    id: '/weight',
    path: '/weight',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125PartnersPortalRoute =
  Char123LangChar125PartnersPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => Char123LangChar125PartnersRoute,
  } as any)
const Char123LangChar125TrainIndexRoute =
  Char123LangChar125TrainIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125TrainRoute,
  } as any)
const Char123LangChar125TrainJourneyRoute =
  Char123LangChar125TrainJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => Char123LangChar125TrainRoute,
  } as any)
const Char123LangChar125TrainLibraryRoute =
  Char123LangChar125TrainLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => Char123LangChar125TrainRoute,
  } as any)
const Char123LangChar125TrainSetupRoute =
  Char123LangChar125TrainSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => Char123LangChar125TrainRoute,
  } as any)
const Char123LangChar125TravelIndexRoute =
  Char123LangChar125TravelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125TravelRoute,
  } as any)
const Char123LangChar125TravelAbroadRoute =
  Char123LangChar125TravelAbroadRouteImport.update({
    id: '/abroad',
    path: '/abroad',
    getParentRoute: () => Char123LangChar125TravelRoute,
  } as any)
const Char123LangChar125TravelCarRoute =
  Char123LangChar125TravelCarRouteImport.update({
    id: '/car',
    path: '/car',
    getParentRoute: () => Char123LangChar125TravelRoute,
  } as any)
const Char123LangChar125TravelOutdoorsRoute =
  Char123LangChar125TravelOutdoorsRouteImport.update({
    id: '/outdoors',
    path: '/outdoors',
    getParentRoute: () => Char123LangChar125TravelRoute,
  } as any)
const Char123LangChar125VerifyMemberIdRoute =
  Char123LangChar125VerifyMemberIdRouteImport.update({
    id: '/verify/$memberId',
    path: '/verify/$memberId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125GetADogBreedBreedIdRoute =
  Char123LangChar125GetADogBreedBreedIdRouteImport.update({
    id: '/breed/$breedId',
    path: '/breed/$breedId',
    getParentRoute: () => Char123LangChar125GetADogRoute,
  } as any)
const Char123LangChar125MyDogCareTopicIdRoute =
  Char123LangChar125MyDogCareTopicIdRouteImport.update({
    id: '/care/$topicId',
    path: '/care/$topicId',
    getParentRoute: () => Char123LangChar125MyDogRoute,
  } as any)
const Char123LangChar125TrainLessonsLessonIdRoute =
  Char123LangChar125TrainLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => Char123LangChar125TrainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountRoute
  '/{-$lang}/auth': typeof Char123LangChar125AuthRoute
  '/{-$lang}/best-apartment-dogs': typeof Char123LangChar125BestApartmentDogsRoute
  '/{-$lang}/best-dog-breeds-for-families': typeof Char123LangChar125BestDogBreedsForFamiliesRoute
  '/{-$lang}/best-dogs-for-first-time-owners': typeof Char123LangChar125BestDogsForFirstTimeOwnersRoute
  '/{-$lang}/brochure': typeof Char123LangChar125BrochureRoute
  '/{-$lang}/compare': typeof Char123LangChar125CompareRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/dog-life': typeof Char123LangChar125DogLifeRoute
  '/{-$lang}/dogs-that-can-be-left-alone': typeof Char123LangChar125DogsThatCanBeLeftAloneRoute
  '/{-$lang}/find-my-dog': typeof Char123LangChar125FindMyDogRoute
  '/{-$lang}/get-a-dog': typeof Char123LangChar125GetADogRouteWithChildren
  '/{-$lang}/guides': typeof Char123LangChar125GuidesRoute
  '/{-$lang}/low-shedding-dogs': typeof Char123LangChar125LowSheddingDogsRoute
  '/{-$lang}/member-card': typeof Char123LangChar125MemberCardRoute
  '/{-$lang}/most-mismatched-breeds': typeof Char123LangChar125MostMismatchedBreedsRoute
  '/{-$lang}/my-dog': typeof Char123LangChar125MyDogRouteWithChildren
  '/{-$lang}/partners': typeof Char123LangChar125PartnersRouteWithChildren
  '/{-$lang}/plus': typeof Char123LangChar125PlusRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/sources': typeof Char123LangChar125SourcesRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}/train': typeof Char123LangChar125TrainRouteWithChildren
  '/{-$lang}/travel': typeof Char123LangChar125TravelRouteWithChildren
  '/{-$lang}/what-a-dog-costs': typeof Char123LangChar125WhatADogCostsRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/breeds/$breedId': typeof Char123LangChar125BreedsBreedIdRoute
  '/{-$lang}/can-dogs-eat/$foodId': typeof Char123LangChar125CanDogsEatFoodIdRoute
  '/{-$lang}/checkout/canceled': typeof Char123LangChar125CheckoutCanceledRoute
  '/{-$lang}/checkout/success': typeof Char123LangChar125CheckoutSuccessRoute
  '/{-$lang}/get-a-dog/choose': typeof Char123LangChar125GetADogChooseRoute
  '/{-$lang}/get-a-dog/costs': typeof Char123LangChar125GetADogCostsRoute
  '/{-$lang}/get-a-dog/prepare': typeof Char123LangChar125GetADogPrepareRoute
  '/{-$lang}/get-a-dog/ready': typeof Char123LangChar125GetADogReadyRoute
  '/{-$lang}/get-a-dog/welcome-home': typeof Char123LangChar125GetADogWelcomeHomeRoute
  '/{-$lang}/my-dog/contacts': typeof Char123LangChar125MyDogContactsRoute
  '/{-$lang}/my-dog/food': typeof Char123LangChar125MyDogFoodRoute
  '/{-$lang}/my-dog/nutrition': typeof Char123LangChar125MyDogNutritionRoute
  '/{-$lang}/my-dog/pack': typeof Char123LangChar125MyDogPackRoute
  '/{-$lang}/my-dog/preview': typeof Char123LangChar125MyDogPreviewRoute
  '/{-$lang}/my-dog/print': typeof Char123LangChar125MyDogPrintRoute
  '/{-$lang}/my-dog/setup': typeof Char123LangChar125MyDogSetupRoute
  '/{-$lang}/my-dog/vet': typeof Char123LangChar125MyDogVetRoute
  '/{-$lang}/my-dog/week': typeof Char123LangChar125MyDogWeekRoute
  '/{-$lang}/my-dog/weight': typeof Char123LangChar125MyDogWeightRoute
  '/{-$lang}/partners/portal': typeof Char123LangChar125PartnersPortalRoute
  '/{-$lang}/train/journey': typeof Char123LangChar125TrainJourneyRoute
  '/{-$lang}/train/library': typeof Char123LangChar125TrainLibraryRoute
  '/{-$lang}/train/setup': typeof Char123LangChar125TrainSetupRoute
  '/{-$lang}/travel/abroad': typeof Char123LangChar125TravelAbroadRoute
  '/{-$lang}/travel/car': typeof Char123LangChar125TravelCarRoute
  '/{-$lang}/travel/outdoors': typeof Char123LangChar125TravelOutdoorsRoute
  '/{-$lang}/verify/$memberId': typeof Char123LangChar125VerifyMemberIdRoute
  '/{-$lang}/breeds/': typeof Char123LangChar125BreedsIndexRoute
  '/{-$lang}/can-dogs-eat/': typeof Char123LangChar125CanDogsEatIndexRoute
  '/{-$lang}/get-a-dog/': typeof Char123LangChar125GetADogIndexRoute
  '/{-$lang}/my-dog/': typeof Char123LangChar125MyDogIndexRoute
  '/{-$lang}/train/': typeof Char123LangChar125TrainIndexRoute
  '/{-$lang}/travel/': typeof Char123LangChar125TravelIndexRoute
  '/{-$lang}/get-a-dog/breed/$breedId': typeof Char123LangChar125GetADogBreedBreedIdRoute
  '/{-$lang}/my-dog/care/$topicId': typeof Char123LangChar125MyDogCareTopicIdRoute
  '/{-$lang}/train/lessons/$lessonId': typeof Char123LangChar125TrainLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountRoute
  '/{-$lang}/auth': typeof Char123LangChar125AuthRoute
  '/{-$lang}/best-apartment-dogs': typeof Char123LangChar125BestApartmentDogsRoute
  '/{-$lang}/best-dog-breeds-for-families': typeof Char123LangChar125BestDogBreedsForFamiliesRoute
  '/{-$lang}/best-dogs-for-first-time-owners': typeof Char123LangChar125BestDogsForFirstTimeOwnersRoute
  '/{-$lang}/brochure': typeof Char123LangChar125BrochureRoute
  '/{-$lang}/compare': typeof Char123LangChar125CompareRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/dog-life': typeof Char123LangChar125DogLifeRoute
  '/{-$lang}/dogs-that-can-be-left-alone': typeof Char123LangChar125DogsThatCanBeLeftAloneRoute
  '/{-$lang}/find-my-dog': typeof Char123LangChar125FindMyDogRoute
  '/{-$lang}/guides': typeof Char123LangChar125GuidesRoute
  '/{-$lang}/low-shedding-dogs': typeof Char123LangChar125LowSheddingDogsRoute
  '/{-$lang}/member-card': typeof Char123LangChar125MemberCardRoute
  '/{-$lang}/most-mismatched-breeds': typeof Char123LangChar125MostMismatchedBreedsRoute
  '/{-$lang}/partners': typeof Char123LangChar125PartnersRouteWithChildren
  '/{-$lang}/plus': typeof Char123LangChar125PlusRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/sources': typeof Char123LangChar125SourcesRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}/what-a-dog-costs': typeof Char123LangChar125WhatADogCostsRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/breeds/$breedId': typeof Char123LangChar125BreedsBreedIdRoute
  '/{-$lang}/can-dogs-eat/$foodId': typeof Char123LangChar125CanDogsEatFoodIdRoute
  '/{-$lang}/checkout/canceled': typeof Char123LangChar125CheckoutCanceledRoute
  '/{-$lang}/checkout/success': typeof Char123LangChar125CheckoutSuccessRoute
  '/{-$lang}/get-a-dog/choose': typeof Char123LangChar125GetADogChooseRoute
  '/{-$lang}/get-a-dog/costs': typeof Char123LangChar125GetADogCostsRoute
  '/{-$lang}/get-a-dog/prepare': typeof Char123LangChar125GetADogPrepareRoute
  '/{-$lang}/get-a-dog/ready': typeof Char123LangChar125GetADogReadyRoute
  '/{-$lang}/get-a-dog/welcome-home': typeof Char123LangChar125GetADogWelcomeHomeRoute
  '/{-$lang}/my-dog/contacts': typeof Char123LangChar125MyDogContactsRoute
  '/{-$lang}/my-dog/food': typeof Char123LangChar125MyDogFoodRoute
  '/{-$lang}/my-dog/nutrition': typeof Char123LangChar125MyDogNutritionRoute
  '/{-$lang}/my-dog/pack': typeof Char123LangChar125MyDogPackRoute
  '/{-$lang}/my-dog/preview': typeof Char123LangChar125MyDogPreviewRoute
  '/{-$lang}/my-dog/print': typeof Char123LangChar125MyDogPrintRoute
  '/{-$lang}/my-dog/setup': typeof Char123LangChar125MyDogSetupRoute
  '/{-$lang}/my-dog/vet': typeof Char123LangChar125MyDogVetRoute
  '/{-$lang}/my-dog/week': typeof Char123LangChar125MyDogWeekRoute
  '/{-$lang}/my-dog/weight': typeof Char123LangChar125MyDogWeightRoute
  '/{-$lang}/partners/portal': typeof Char123LangChar125PartnersPortalRoute
  '/{-$lang}/train/journey': typeof Char123LangChar125TrainJourneyRoute
  '/{-$lang}/train/library': typeof Char123LangChar125TrainLibraryRoute
  '/{-$lang}/train/setup': typeof Char123LangChar125TrainSetupRoute
  '/{-$lang}/travel/abroad': typeof Char123LangChar125TravelAbroadRoute
  '/{-$lang}/travel/car': typeof Char123LangChar125TravelCarRoute
  '/{-$lang}/travel/outdoors': typeof Char123LangChar125TravelOutdoorsRoute
  '/{-$lang}/verify/$memberId': typeof Char123LangChar125VerifyMemberIdRoute
  '/{-$lang}/breeds': typeof Char123LangChar125BreedsIndexRoute
  '/{-$lang}/can-dogs-eat': typeof Char123LangChar125CanDogsEatIndexRoute
  '/{-$lang}/get-a-dog': typeof Char123LangChar125GetADogIndexRoute
  '/{-$lang}/my-dog': typeof Char123LangChar125MyDogIndexRoute
  '/{-$lang}/train': typeof Char123LangChar125TrainIndexRoute
  '/{-$lang}/travel': typeof Char123LangChar125TravelIndexRoute
  '/{-$lang}/get-a-dog/breed/$breedId': typeof Char123LangChar125GetADogBreedBreedIdRoute
  '/{-$lang}/my-dog/care/$topicId': typeof Char123LangChar125MyDogCareTopicIdRoute
  '/{-$lang}/train/lessons/$lessonId': typeof Char123LangChar125TrainLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountRoute
  '/{-$lang}/auth': typeof Char123LangChar125AuthRoute
  '/{-$lang}/best-apartment-dogs': typeof Char123LangChar125BestApartmentDogsRoute
  '/{-$lang}/best-dog-breeds-for-families': typeof Char123LangChar125BestDogBreedsForFamiliesRoute
  '/{-$lang}/best-dogs-for-first-time-owners': typeof Char123LangChar125BestDogsForFirstTimeOwnersRoute
  '/{-$lang}/brochure': typeof Char123LangChar125BrochureRoute
  '/{-$lang}/compare': typeof Char123LangChar125CompareRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/dog-life': typeof Char123LangChar125DogLifeRoute
  '/{-$lang}/dogs-that-can-be-left-alone': typeof Char123LangChar125DogsThatCanBeLeftAloneRoute
  '/{-$lang}/find-my-dog': typeof Char123LangChar125FindMyDogRoute
  '/{-$lang}/get-a-dog': typeof Char123LangChar125GetADogRouteWithChildren
  '/{-$lang}/guides': typeof Char123LangChar125GuidesRoute
  '/{-$lang}/low-shedding-dogs': typeof Char123LangChar125LowSheddingDogsRoute
  '/{-$lang}/member-card': typeof Char123LangChar125MemberCardRoute
  '/{-$lang}/most-mismatched-breeds': typeof Char123LangChar125MostMismatchedBreedsRoute
  '/{-$lang}/my-dog': typeof Char123LangChar125MyDogRouteWithChildren
  '/{-$lang}/partners': typeof Char123LangChar125PartnersRouteWithChildren
  '/{-$lang}/plus': typeof Char123LangChar125PlusRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/sources': typeof Char123LangChar125SourcesRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}/train': typeof Char123LangChar125TrainRouteWithChildren
  '/{-$lang}/travel': typeof Char123LangChar125TravelRouteWithChildren
  '/{-$lang}/what-a-dog-costs': typeof Char123LangChar125WhatADogCostsRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/breeds/$breedId': typeof Char123LangChar125BreedsBreedIdRoute
  '/{-$lang}/can-dogs-eat/$foodId': typeof Char123LangChar125CanDogsEatFoodIdRoute
  '/{-$lang}/checkout/canceled': typeof Char123LangChar125CheckoutCanceledRoute
  '/{-$lang}/checkout/success': typeof Char123LangChar125CheckoutSuccessRoute
  '/{-$lang}/get-a-dog/choose': typeof Char123LangChar125GetADogChooseRoute
  '/{-$lang}/get-a-dog/costs': typeof Char123LangChar125GetADogCostsRoute
  '/{-$lang}/get-a-dog/prepare': typeof Char123LangChar125GetADogPrepareRoute
  '/{-$lang}/get-a-dog/ready': typeof Char123LangChar125GetADogReadyRoute
  '/{-$lang}/get-a-dog/welcome-home': typeof Char123LangChar125GetADogWelcomeHomeRoute
  '/{-$lang}/my-dog/contacts': typeof Char123LangChar125MyDogContactsRoute
  '/{-$lang}/my-dog/food': typeof Char123LangChar125MyDogFoodRoute
  '/{-$lang}/my-dog/nutrition': typeof Char123LangChar125MyDogNutritionRoute
  '/{-$lang}/my-dog/pack': typeof Char123LangChar125MyDogPackRoute
  '/{-$lang}/my-dog/preview': typeof Char123LangChar125MyDogPreviewRoute
  '/{-$lang}/my-dog/print': typeof Char123LangChar125MyDogPrintRoute
  '/{-$lang}/my-dog/setup': typeof Char123LangChar125MyDogSetupRoute
  '/{-$lang}/my-dog/vet': typeof Char123LangChar125MyDogVetRoute
  '/{-$lang}/my-dog/week': typeof Char123LangChar125MyDogWeekRoute
  '/{-$lang}/my-dog/weight': typeof Char123LangChar125MyDogWeightRoute
  '/{-$lang}/partners/portal': typeof Char123LangChar125PartnersPortalRoute
  '/{-$lang}/train/journey': typeof Char123LangChar125TrainJourneyRoute
  '/{-$lang}/train/library': typeof Char123LangChar125TrainLibraryRoute
  '/{-$lang}/train/setup': typeof Char123LangChar125TrainSetupRoute
  '/{-$lang}/travel/abroad': typeof Char123LangChar125TravelAbroadRoute
  '/{-$lang}/travel/car': typeof Char123LangChar125TravelCarRoute
  '/{-$lang}/travel/outdoors': typeof Char123LangChar125TravelOutdoorsRoute
  '/{-$lang}/verify/$memberId': typeof Char123LangChar125VerifyMemberIdRoute
  '/{-$lang}/breeds/': typeof Char123LangChar125BreedsIndexRoute
  '/{-$lang}/can-dogs-eat/': typeof Char123LangChar125CanDogsEatIndexRoute
  '/{-$lang}/get-a-dog/': typeof Char123LangChar125GetADogIndexRoute
  '/{-$lang}/my-dog/': typeof Char123LangChar125MyDogIndexRoute
  '/{-$lang}/train/': typeof Char123LangChar125TrainIndexRoute
  '/{-$lang}/travel/': typeof Char123LangChar125TravelIndexRoute
  '/{-$lang}/get-a-dog/breed/$breedId': typeof Char123LangChar125GetADogBreedBreedIdRoute
  '/{-$lang}/my-dog/care/$topicId': typeof Char123LangChar125MyDogCareTopicIdRoute
  '/{-$lang}/train/lessons/$lessonId': typeof Char123LangChar125TrainLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/{-$lang}'
    | '/{-$lang}/about'
    | '/{-$lang}/account'
    | '/{-$lang}/auth'
    | '/{-$lang}/best-apartment-dogs'
    | '/{-$lang}/best-dog-breeds-for-families'
    | '/{-$lang}/best-dogs-for-first-time-owners'
    | '/{-$lang}/brochure'
    | '/{-$lang}/compare'
    | '/{-$lang}/contact'
    | '/{-$lang}/dog-life'
    | '/{-$lang}/dogs-that-can-be-left-alone'
    | '/{-$lang}/find-my-dog'
    | '/{-$lang}/get-a-dog'
    | '/{-$lang}/guides'
    | '/{-$lang}/low-shedding-dogs'
    | '/{-$lang}/member-card'
    | '/{-$lang}/most-mismatched-breeds'
    | '/{-$lang}/my-dog'
    | '/{-$lang}/partners'
    | '/{-$lang}/plus'
    | '/{-$lang}/privacy'
    | '/{-$lang}/sources'
    | '/{-$lang}/terms'
    | '/{-$lang}/train'
    | '/{-$lang}/travel'
    | '/{-$lang}/what-a-dog-costs'
    | '/{-$lang}/'
    | '/{-$lang}/breeds/$breedId'
    | '/{-$lang}/can-dogs-eat/$foodId'
    | '/{-$lang}/checkout/canceled'
    | '/{-$lang}/checkout/success'
    | '/{-$lang}/get-a-dog/choose'
    | '/{-$lang}/get-a-dog/costs'
    | '/{-$lang}/get-a-dog/prepare'
    | '/{-$lang}/get-a-dog/ready'
    | '/{-$lang}/get-a-dog/welcome-home'
    | '/{-$lang}/my-dog/contacts'
    | '/{-$lang}/my-dog/food'
    | '/{-$lang}/my-dog/nutrition'
    | '/{-$lang}/my-dog/pack'
    | '/{-$lang}/my-dog/preview'
    | '/{-$lang}/my-dog/print'
    | '/{-$lang}/my-dog/setup'
    | '/{-$lang}/my-dog/vet'
    | '/{-$lang}/my-dog/week'
    | '/{-$lang}/my-dog/weight'
    | '/{-$lang}/partners/portal'
    | '/{-$lang}/train/journey'
    | '/{-$lang}/train/library'
    | '/{-$lang}/train/setup'
    | '/{-$lang}/travel/abroad'
    | '/{-$lang}/travel/car'
    | '/{-$lang}/travel/outdoors'
    | '/{-$lang}/verify/$memberId'
    | '/{-$lang}/breeds/'
    | '/{-$lang}/can-dogs-eat/'
    | '/{-$lang}/get-a-dog/'
    | '/{-$lang}/my-dog/'
    | '/{-$lang}/train/'
    | '/{-$lang}/travel/'
    | '/{-$lang}/get-a-dog/breed/$breedId'
    | '/{-$lang}/my-dog/care/$topicId'
    | '/{-$lang}/train/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$lang}/about'
    | '/{-$lang}/account'
    | '/{-$lang}/auth'
    | '/{-$lang}/best-apartment-dogs'
    | '/{-$lang}/best-dog-breeds-for-families'
    | '/{-$lang}/best-dogs-for-first-time-owners'
    | '/{-$lang}/brochure'
    | '/{-$lang}/compare'
    | '/{-$lang}/contact'
    | '/{-$lang}/dog-life'
    | '/{-$lang}/dogs-that-can-be-left-alone'
    | '/{-$lang}/find-my-dog'
    | '/{-$lang}/guides'
    | '/{-$lang}/low-shedding-dogs'
    | '/{-$lang}/member-card'
    | '/{-$lang}/most-mismatched-breeds'
    | '/{-$lang}/partners'
    | '/{-$lang}/plus'
    | '/{-$lang}/privacy'
    | '/{-$lang}/sources'
    | '/{-$lang}/terms'
    | '/{-$lang}/what-a-dog-costs'
    | '/{-$lang}'
    | '/{-$lang}/breeds/$breedId'
    | '/{-$lang}/can-dogs-eat/$foodId'
    | '/{-$lang}/checkout/canceled'
    | '/{-$lang}/checkout/success'
    | '/{-$lang}/get-a-dog/choose'
    | '/{-$lang}/get-a-dog/costs'
    | '/{-$lang}/get-a-dog/prepare'
    | '/{-$lang}/get-a-dog/ready'
    | '/{-$lang}/get-a-dog/welcome-home'
    | '/{-$lang}/my-dog/contacts'
    | '/{-$lang}/my-dog/food'
    | '/{-$lang}/my-dog/nutrition'
    | '/{-$lang}/my-dog/pack'
    | '/{-$lang}/my-dog/preview'
    | '/{-$lang}/my-dog/print'
    | '/{-$lang}/my-dog/setup'
    | '/{-$lang}/my-dog/vet'
    | '/{-$lang}/my-dog/week'
    | '/{-$lang}/my-dog/weight'
    | '/{-$lang}/partners/portal'
    | '/{-$lang}/train/journey'
    | '/{-$lang}/train/library'
    | '/{-$lang}/train/setup'
    | '/{-$lang}/travel/abroad'
    | '/{-$lang}/travel/car'
    | '/{-$lang}/travel/outdoors'
    | '/{-$lang}/verify/$memberId'
    | '/{-$lang}/breeds'
    | '/{-$lang}/can-dogs-eat'
    | '/{-$lang}/get-a-dog'
    | '/{-$lang}/my-dog'
    | '/{-$lang}/train'
    | '/{-$lang}/travel'
    | '/{-$lang}/get-a-dog/breed/$breedId'
    | '/{-$lang}/my-dog/care/$topicId'
    | '/{-$lang}/train/lessons/$lessonId'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/{-$lang}'
    | '/{-$lang}/about'
    | '/{-$lang}/account'
    | '/{-$lang}/auth'
    | '/{-$lang}/best-apartment-dogs'
    | '/{-$lang}/best-dog-breeds-for-families'
    | '/{-$lang}/best-dogs-for-first-time-owners'
    | '/{-$lang}/brochure'
    | '/{-$lang}/compare'
    | '/{-$lang}/contact'
    | '/{-$lang}/dog-life'
    | '/{-$lang}/dogs-that-can-be-left-alone'
    | '/{-$lang}/find-my-dog'
    | '/{-$lang}/get-a-dog'
    | '/{-$lang}/guides'
    | '/{-$lang}/low-shedding-dogs'
    | '/{-$lang}/member-card'
    | '/{-$lang}/most-mismatched-breeds'
    | '/{-$lang}/my-dog'
    | '/{-$lang}/partners'
    | '/{-$lang}/plus'
    | '/{-$lang}/privacy'
    | '/{-$lang}/sources'
    | '/{-$lang}/terms'
    | '/{-$lang}/train'
    | '/{-$lang}/travel'
    | '/{-$lang}/what-a-dog-costs'
    | '/{-$lang}/'
    | '/{-$lang}/breeds/$breedId'
    | '/{-$lang}/can-dogs-eat/$foodId'
    | '/{-$lang}/checkout/canceled'
    | '/{-$lang}/checkout/success'
    | '/{-$lang}/get-a-dog/choose'
    | '/{-$lang}/get-a-dog/costs'
    | '/{-$lang}/get-a-dog/prepare'
    | '/{-$lang}/get-a-dog/ready'
    | '/{-$lang}/get-a-dog/welcome-home'
    | '/{-$lang}/my-dog/contacts'
    | '/{-$lang}/my-dog/food'
    | '/{-$lang}/my-dog/nutrition'
    | '/{-$lang}/my-dog/pack'
    | '/{-$lang}/my-dog/preview'
    | '/{-$lang}/my-dog/print'
    | '/{-$lang}/my-dog/setup'
    | '/{-$lang}/my-dog/vet'
    | '/{-$lang}/my-dog/week'
    | '/{-$lang}/my-dog/weight'
    | '/{-$lang}/partners/portal'
    | '/{-$lang}/train/journey'
    | '/{-$lang}/train/library'
    | '/{-$lang}/train/setup'
    | '/{-$lang}/travel/abroad'
    | '/{-$lang}/travel/car'
    | '/{-$lang}/travel/outdoors'
    | '/{-$lang}/verify/$memberId'
    | '/{-$lang}/breeds/'
    | '/{-$lang}/can-dogs-eat/'
    | '/{-$lang}/get-a-dog/'
    | '/{-$lang}/my-dog/'
    | '/{-$lang}/train/'
    | '/{-$lang}/travel/'
    | '/{-$lang}/get-a-dog/breed/$breedId'
    | '/{-$lang}/my-dog/care/$topicId'
    | '/{-$lang}/train/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LangChar125Route: typeof Char123LangChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/about': {
      id: '/{-$lang}/about'
      path: '/about'
      fullPath: '/{-$lang}/about'
      preLoaderRoute: typeof Char123LangChar125AboutRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/account': {
      id: '/{-$lang}/account'
      path: '/account'
      fullPath: '/{-$lang}/account'
      preLoaderRoute: typeof Char123LangChar125AccountRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/auth': {
      id: '/{-$lang}/auth'
      path: '/auth'
      fullPath: '/{-$lang}/auth'
      preLoaderRoute: typeof Char123LangChar125AuthRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/best-apartment-dogs': {
      id: '/{-$lang}/best-apartment-dogs'
      path: '/best-apartment-dogs'
      fullPath: '/{-$lang}/best-apartment-dogs'
      preLoaderRoute: typeof Char123LangChar125BestApartmentDogsRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/best-dog-breeds-for-families': {
      id: '/{-$lang}/best-dog-breeds-for-families'
      path: '/best-dog-breeds-for-families'
      fullPath: '/{-$lang}/best-dog-breeds-for-families'
      preLoaderRoute: typeof Char123LangChar125BestDogBreedsForFamiliesRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/best-dogs-for-first-time-owners': {
      id: '/{-$lang}/best-dogs-for-first-time-owners'
      path: '/best-dogs-for-first-time-owners'
      fullPath: '/{-$lang}/best-dogs-for-first-time-owners'
      preLoaderRoute: typeof Char123LangChar125BestDogsForFirstTimeOwnersRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/brochure': {
      id: '/{-$lang}/brochure'
      path: '/brochure'
      fullPath: '/{-$lang}/brochure'
      preLoaderRoute: typeof Char123LangChar125BrochureRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/compare': {
      id: '/{-$lang}/compare'
      path: '/compare'
      fullPath: '/{-$lang}/compare'
      preLoaderRoute: typeof Char123LangChar125CompareRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/dog-life': {
      id: '/{-$lang}/dog-life'
      path: '/dog-life'
      fullPath: '/{-$lang}/dog-life'
      preLoaderRoute: typeof Char123LangChar125DogLifeRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/dogs-that-can-be-left-alone': {
      id: '/{-$lang}/dogs-that-can-be-left-alone'
      path: '/dogs-that-can-be-left-alone'
      fullPath: '/{-$lang}/dogs-that-can-be-left-alone'
      preLoaderRoute: typeof Char123LangChar125DogsThatCanBeLeftAloneRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/find-my-dog': {
      id: '/{-$lang}/find-my-dog'
      path: '/find-my-dog'
      fullPath: '/{-$lang}/find-my-dog'
      preLoaderRoute: typeof Char123LangChar125FindMyDogRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/get-a-dog': {
      id: '/{-$lang}/get-a-dog'
      path: '/get-a-dog'
      fullPath: '/{-$lang}/get-a-dog'
      preLoaderRoute: typeof Char123LangChar125GetADogRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/guides': {
      id: '/{-$lang}/guides'
      path: '/guides'
      fullPath: '/{-$lang}/guides'
      preLoaderRoute: typeof Char123LangChar125GuidesRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/low-shedding-dogs': {
      id: '/{-$lang}/low-shedding-dogs'
      path: '/low-shedding-dogs'
      fullPath: '/{-$lang}/low-shedding-dogs'
      preLoaderRoute: typeof Char123LangChar125LowSheddingDogsRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/member-card': {
      id: '/{-$lang}/member-card'
      path: '/member-card'
      fullPath: '/{-$lang}/member-card'
      preLoaderRoute: typeof Char123LangChar125MemberCardRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/most-mismatched-breeds': {
      id: '/{-$lang}/most-mismatched-breeds'
      path: '/most-mismatched-breeds'
      fullPath: '/{-$lang}/most-mismatched-breeds'
      preLoaderRoute: typeof Char123LangChar125MostMismatchedBreedsRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/my-dog': {
      id: '/{-$lang}/my-dog'
      path: '/my-dog'
      fullPath: '/{-$lang}/my-dog'
      preLoaderRoute: typeof Char123LangChar125MyDogRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/partners': {
      id: '/{-$lang}/partners'
      path: '/partners'
      fullPath: '/{-$lang}/partners'
      preLoaderRoute: typeof Char123LangChar125PartnersRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/plus': {
      id: '/{-$lang}/plus'
      path: '/plus'
      fullPath: '/{-$lang}/plus'
      preLoaderRoute: typeof Char123LangChar125PlusRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/privacy': {
      id: '/{-$lang}/privacy'
      path: '/privacy'
      fullPath: '/{-$lang}/privacy'
      preLoaderRoute: typeof Char123LangChar125PrivacyRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/sources': {
      id: '/{-$lang}/sources'
      path: '/sources'
      fullPath: '/{-$lang}/sources'
      preLoaderRoute: typeof Char123LangChar125SourcesRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/terms': {
      id: '/{-$lang}/terms'
      path: '/terms'
      fullPath: '/{-$lang}/terms'
      preLoaderRoute: typeof Char123LangChar125TermsRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/train': {
      id: '/{-$lang}/train'
      path: '/train'
      fullPath: '/{-$lang}/train'
      preLoaderRoute: typeof Char123LangChar125TrainRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/travel': {
      id: '/{-$lang}/travel'
      path: '/travel'
      fullPath: '/{-$lang}/travel'
      preLoaderRoute: typeof Char123LangChar125TravelRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/what-a-dog-costs': {
      id: '/{-$lang}/what-a-dog-costs'
      path: '/what-a-dog-costs'
      fullPath: '/{-$lang}/what-a-dog-costs'
      preLoaderRoute: typeof Char123LangChar125WhatADogCostsRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/breeds/': {
      id: '/{-$lang}/breeds/'
      path: '/breeds'
      fullPath: '/{-$lang}/breeds/'
      preLoaderRoute: typeof Char123LangChar125BreedsIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/breeds/$breedId': {
      id: '/{-$lang}/breeds/$breedId'
      path: '/breeds/$breedId'
      fullPath: '/{-$lang}/breeds/$breedId'
      preLoaderRoute: typeof Char123LangChar125BreedsBreedIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/can-dogs-eat/': {
      id: '/{-$lang}/can-dogs-eat/'
      path: '/can-dogs-eat'
      fullPath: '/{-$lang}/can-dogs-eat/'
      preLoaderRoute: typeof Char123LangChar125CanDogsEatIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/can-dogs-eat/$foodId': {
      id: '/{-$lang}/can-dogs-eat/$foodId'
      path: '/can-dogs-eat/$foodId'
      fullPath: '/{-$lang}/can-dogs-eat/$foodId'
      preLoaderRoute: typeof Char123LangChar125CanDogsEatFoodIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/checkout/canceled': {
      id: '/{-$lang}/checkout/canceled'
      path: '/checkout/canceled'
      fullPath: '/{-$lang}/checkout/canceled'
      preLoaderRoute: typeof Char123LangChar125CheckoutCanceledRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/checkout/success': {
      id: '/{-$lang}/checkout/success'
      path: '/checkout/success'
      fullPath: '/{-$lang}/checkout/success'
      preLoaderRoute: typeof Char123LangChar125CheckoutSuccessRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/get-a-dog/': {
      id: '/{-$lang}/get-a-dog/'
      path: '/'
      fullPath: '/{-$lang}/get-a-dog/'
      preLoaderRoute: typeof Char123LangChar125GetADogIndexRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/get-a-dog/choose': {
      id: '/{-$lang}/get-a-dog/choose'
      path: '/choose'
      fullPath: '/{-$lang}/get-a-dog/choose'
      preLoaderRoute: typeof Char123LangChar125GetADogChooseRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/get-a-dog/costs': {
      id: '/{-$lang}/get-a-dog/costs'
      path: '/costs'
      fullPath: '/{-$lang}/get-a-dog/costs'
      preLoaderRoute: typeof Char123LangChar125GetADogCostsRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/get-a-dog/prepare': {
      id: '/{-$lang}/get-a-dog/prepare'
      path: '/prepare'
      fullPath: '/{-$lang}/get-a-dog/prepare'
      preLoaderRoute: typeof Char123LangChar125GetADogPrepareRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/get-a-dog/ready': {
      id: '/{-$lang}/get-a-dog/ready'
      path: '/ready'
      fullPath: '/{-$lang}/get-a-dog/ready'
      preLoaderRoute: typeof Char123LangChar125GetADogReadyRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/get-a-dog/welcome-home': {
      id: '/{-$lang}/get-a-dog/welcome-home'
      path: '/welcome-home'
      fullPath: '/{-$lang}/get-a-dog/welcome-home'
      preLoaderRoute: typeof Char123LangChar125GetADogWelcomeHomeRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/my-dog/': {
      id: '/{-$lang}/my-dog/'
      path: '/'
      fullPath: '/{-$lang}/my-dog/'
      preLoaderRoute: typeof Char123LangChar125MyDogIndexRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/contacts': {
      id: '/{-$lang}/my-dog/contacts'
      path: '/contacts'
      fullPath: '/{-$lang}/my-dog/contacts'
      preLoaderRoute: typeof Char123LangChar125MyDogContactsRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/food': {
      id: '/{-$lang}/my-dog/food'
      path: '/food'
      fullPath: '/{-$lang}/my-dog/food'
      preLoaderRoute: typeof Char123LangChar125MyDogFoodRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/nutrition': {
      id: '/{-$lang}/my-dog/nutrition'
      path: '/nutrition'
      fullPath: '/{-$lang}/my-dog/nutrition'
      preLoaderRoute: typeof Char123LangChar125MyDogNutritionRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/pack': {
      id: '/{-$lang}/my-dog/pack'
      path: '/pack'
      fullPath: '/{-$lang}/my-dog/pack'
      preLoaderRoute: typeof Char123LangChar125MyDogPackRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/preview': {
      id: '/{-$lang}/my-dog/preview'
      path: '/preview'
      fullPath: '/{-$lang}/my-dog/preview'
      preLoaderRoute: typeof Char123LangChar125MyDogPreviewRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/print': {
      id: '/{-$lang}/my-dog/print'
      path: '/print'
      fullPath: '/{-$lang}/my-dog/print'
      preLoaderRoute: typeof Char123LangChar125MyDogPrintRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/setup': {
      id: '/{-$lang}/my-dog/setup'
      path: '/setup'
      fullPath: '/{-$lang}/my-dog/setup'
      preLoaderRoute: typeof Char123LangChar125MyDogSetupRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/vet': {
      id: '/{-$lang}/my-dog/vet'
      path: '/vet'
      fullPath: '/{-$lang}/my-dog/vet'
      preLoaderRoute: typeof Char123LangChar125MyDogVetRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/week': {
      id: '/{-$lang}/my-dog/week'
      path: '/week'
      fullPath: '/{-$lang}/my-dog/week'
      preLoaderRoute: typeof Char123LangChar125MyDogWeekRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/my-dog/weight': {
      id: '/{-$lang}/my-dog/weight'
      path: '/weight'
      fullPath: '/{-$lang}/my-dog/weight'
      preLoaderRoute: typeof Char123LangChar125MyDogWeightRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/partners/portal': {
      id: '/{-$lang}/partners/portal'
      path: '/portal'
      fullPath: '/{-$lang}/partners/portal'
      preLoaderRoute: typeof Char123LangChar125PartnersPortalRouteImport
      parentRoute: typeof Char123LangChar125PartnersRoute
    }
    '/{-$lang}/train/': {
      id: '/{-$lang}/train/'
      path: '/'
      fullPath: '/{-$lang}/train/'
      preLoaderRoute: typeof Char123LangChar125TrainIndexRouteImport
      parentRoute: typeof Char123LangChar125TrainRoute
    }
    '/{-$lang}/train/journey': {
      id: '/{-$lang}/train/journey'
      path: '/journey'
      fullPath: '/{-$lang}/train/journey'
      preLoaderRoute: typeof Char123LangChar125TrainJourneyRouteImport
      parentRoute: typeof Char123LangChar125TrainRoute
    }
    '/{-$lang}/train/library': {
      id: '/{-$lang}/train/library'
      path: '/library'
      fullPath: '/{-$lang}/train/library'
      preLoaderRoute: typeof Char123LangChar125TrainLibraryRouteImport
      parentRoute: typeof Char123LangChar125TrainRoute
    }
    '/{-$lang}/train/setup': {
      id: '/{-$lang}/train/setup'
      path: '/setup'
      fullPath: '/{-$lang}/train/setup'
      preLoaderRoute: typeof Char123LangChar125TrainSetupRouteImport
      parentRoute: typeof Char123LangChar125TrainRoute
    }
    '/{-$lang}/travel/': {
      id: '/{-$lang}/travel/'
      path: '/'
      fullPath: '/{-$lang}/travel/'
      preLoaderRoute: typeof Char123LangChar125TravelIndexRouteImport
      parentRoute: typeof Char123LangChar125TravelRoute
    }
    '/{-$lang}/travel/abroad': {
      id: '/{-$lang}/travel/abroad'
      path: '/abroad'
      fullPath: '/{-$lang}/travel/abroad'
      preLoaderRoute: typeof Char123LangChar125TravelAbroadRouteImport
      parentRoute: typeof Char123LangChar125TravelRoute
    }
    '/{-$lang}/travel/car': {
      id: '/{-$lang}/travel/car'
      path: '/car'
      fullPath: '/{-$lang}/travel/car'
      preLoaderRoute: typeof Char123LangChar125TravelCarRouteImport
      parentRoute: typeof Char123LangChar125TravelRoute
    }
    '/{-$lang}/travel/outdoors': {
      id: '/{-$lang}/travel/outdoors'
      path: '/outdoors'
      fullPath: '/{-$lang}/travel/outdoors'
      preLoaderRoute: typeof Char123LangChar125TravelOutdoorsRouteImport
      parentRoute: typeof Char123LangChar125TravelRoute
    }
    '/{-$lang}/verify/$memberId': {
      id: '/{-$lang}/verify/$memberId'
      path: '/verify/$memberId'
      fullPath: '/{-$lang}/verify/$memberId'
      preLoaderRoute: typeof Char123LangChar125VerifyMemberIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/get-a-dog/breed/$breedId': {
      id: '/{-$lang}/get-a-dog/breed/$breedId'
      path: '/breed/$breedId'
      fullPath: '/{-$lang}/get-a-dog/breed/$breedId'
      preLoaderRoute: typeof Char123LangChar125GetADogBreedBreedIdRouteImport
      parentRoute: typeof Char123LangChar125GetADogRoute
    }
    '/{-$lang}/my-dog/care/$topicId': {
      id: '/{-$lang}/my-dog/care/$topicId'
      path: '/care/$topicId'
      fullPath: '/{-$lang}/my-dog/care/$topicId'
      preLoaderRoute: typeof Char123LangChar125MyDogCareTopicIdRouteImport
      parentRoute: typeof Char123LangChar125MyDogRoute
    }
    '/{-$lang}/train/lessons/$lessonId': {
      id: '/{-$lang}/train/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/{-$lang}/train/lessons/$lessonId'
      preLoaderRoute: typeof Char123LangChar125TrainLessonsLessonIdRouteImport
      parentRoute: typeof Char123LangChar125TrainRoute
    }
  }
}

interface Char123LangChar125GetADogRouteChildren {
  Char123LangChar125GetADogChooseRoute: typeof Char123LangChar125GetADogChooseRoute
  Char123LangChar125GetADogCostsRoute: typeof Char123LangChar125GetADogCostsRoute
  Char123LangChar125GetADogPrepareRoute: typeof Char123LangChar125GetADogPrepareRoute
  Char123LangChar125GetADogReadyRoute: typeof Char123LangChar125GetADogReadyRoute
  Char123LangChar125GetADogWelcomeHomeRoute: typeof Char123LangChar125GetADogWelcomeHomeRoute
  Char123LangChar125GetADogIndexRoute: typeof Char123LangChar125GetADogIndexRoute
  Char123LangChar125GetADogBreedBreedIdRoute: typeof Char123LangChar125GetADogBreedBreedIdRoute
}

const Char123LangChar125GetADogRouteChildren: Char123LangChar125GetADogRouteChildren =
  {
    Char123LangChar125GetADogChooseRoute: Char123LangChar125GetADogChooseRoute,
    Char123LangChar125GetADogCostsRoute: Char123LangChar125GetADogCostsRoute,
    Char123LangChar125GetADogPrepareRoute:
      Char123LangChar125GetADogPrepareRoute,
    Char123LangChar125GetADogReadyRoute: Char123LangChar125GetADogReadyRoute,
    Char123LangChar125GetADogWelcomeHomeRoute:
      Char123LangChar125GetADogWelcomeHomeRoute,
    Char123LangChar125GetADogIndexRoute: Char123LangChar125GetADogIndexRoute,
    Char123LangChar125GetADogBreedBreedIdRoute:
      Char123LangChar125GetADogBreedBreedIdRoute,
  }

const Char123LangChar125GetADogRouteWithChildren =
  Char123LangChar125GetADogRoute._addFileChildren(
    Char123LangChar125GetADogRouteChildren,
  )

interface Char123LangChar125MyDogRouteChildren {
  Char123LangChar125MyDogContactsRoute: typeof Char123LangChar125MyDogContactsRoute
  Char123LangChar125MyDogFoodRoute: typeof Char123LangChar125MyDogFoodRoute
  Char123LangChar125MyDogNutritionRoute: typeof Char123LangChar125MyDogNutritionRoute
  Char123LangChar125MyDogPackRoute: typeof Char123LangChar125MyDogPackRoute
  Char123LangChar125MyDogPreviewRoute: typeof Char123LangChar125MyDogPreviewRoute
  Char123LangChar125MyDogPrintRoute: typeof Char123LangChar125MyDogPrintRoute
  Char123LangChar125MyDogSetupRoute: typeof Char123LangChar125MyDogSetupRoute
  Char123LangChar125MyDogVetRoute: typeof Char123LangChar125MyDogVetRoute
  Char123LangChar125MyDogWeekRoute: typeof Char123LangChar125MyDogWeekRoute
  Char123LangChar125MyDogWeightRoute: typeof Char123LangChar125MyDogWeightRoute
  Char123LangChar125MyDogIndexRoute: typeof Char123LangChar125MyDogIndexRoute
  Char123LangChar125MyDogCareTopicIdRoute: typeof Char123LangChar125MyDogCareTopicIdRoute
}

const Char123LangChar125MyDogRouteChildren: Char123LangChar125MyDogRouteChildren =
  {
    Char123LangChar125MyDogContactsRoute: Char123LangChar125MyDogContactsRoute,
    Char123LangChar125MyDogFoodRoute: Char123LangChar125MyDogFoodRoute,
    Char123LangChar125MyDogNutritionRoute:
      Char123LangChar125MyDogNutritionRoute,
    Char123LangChar125MyDogPackRoute: Char123LangChar125MyDogPackRoute,
    Char123LangChar125MyDogPreviewRoute: Char123LangChar125MyDogPreviewRoute,
    Char123LangChar125MyDogPrintRoute: Char123LangChar125MyDogPrintRoute,
    Char123LangChar125MyDogSetupRoute: Char123LangChar125MyDogSetupRoute,
    Char123LangChar125MyDogVetRoute: Char123LangChar125MyDogVetRoute,
    Char123LangChar125MyDogWeekRoute: Char123LangChar125MyDogWeekRoute,
    Char123LangChar125MyDogWeightRoute: Char123LangChar125MyDogWeightRoute,
    Char123LangChar125MyDogIndexRoute: Char123LangChar125MyDogIndexRoute,
    Char123LangChar125MyDogCareTopicIdRoute:
      Char123LangChar125MyDogCareTopicIdRoute,
  }

const Char123LangChar125MyDogRouteWithChildren =
  Char123LangChar125MyDogRoute._addFileChildren(
    Char123LangChar125MyDogRouteChildren,
  )

interface Char123LangChar125PartnersRouteChildren {
  Char123LangChar125PartnersPortalRoute: typeof Char123LangChar125PartnersPortalRoute
}

const Char123LangChar125PartnersRouteChildren: Char123LangChar125PartnersRouteChildren =
  {
    Char123LangChar125PartnersPortalRoute:
      Char123LangChar125PartnersPortalRoute,
  }

const Char123LangChar125PartnersRouteWithChildren =
  Char123LangChar125PartnersRoute._addFileChildren(
    Char123LangChar125PartnersRouteChildren,
  )

interface Char123LangChar125TrainRouteChildren {
  Char123LangChar125TrainJourneyRoute: typeof Char123LangChar125TrainJourneyRoute
  Char123LangChar125TrainLibraryRoute: typeof Char123LangChar125TrainLibraryRoute
  Char123LangChar125TrainSetupRoute: typeof Char123LangChar125TrainSetupRoute
  Char123LangChar125TrainIndexRoute: typeof Char123LangChar125TrainIndexRoute
  Char123LangChar125TrainLessonsLessonIdRoute: typeof Char123LangChar125TrainLessonsLessonIdRoute
}

const Char123LangChar125TrainRouteChildren: Char123LangChar125TrainRouteChildren =
  {
    Char123LangChar125TrainJourneyRoute: Char123LangChar125TrainJourneyRoute,
    Char123LangChar125TrainLibraryRoute: Char123LangChar125TrainLibraryRoute,
    Char123LangChar125TrainSetupRoute: Char123LangChar125TrainSetupRoute,
    Char123LangChar125TrainIndexRoute: Char123LangChar125TrainIndexRoute,
    Char123LangChar125TrainLessonsLessonIdRoute:
      Char123LangChar125TrainLessonsLessonIdRoute,
  }

const Char123LangChar125TrainRouteWithChildren =
  Char123LangChar125TrainRoute._addFileChildren(
    Char123LangChar125TrainRouteChildren,
  )

interface Char123LangChar125TravelRouteChildren {
  Char123LangChar125TravelAbroadRoute: typeof Char123LangChar125TravelAbroadRoute
  Char123LangChar125TravelCarRoute: typeof Char123LangChar125TravelCarRoute
  Char123LangChar125TravelOutdoorsRoute: typeof Char123LangChar125TravelOutdoorsRoute
  Char123LangChar125TravelIndexRoute: typeof Char123LangChar125TravelIndexRoute
}

const Char123LangChar125TravelRouteChildren: Char123LangChar125TravelRouteChildren =
  {
    Char123LangChar125TravelAbroadRoute: Char123LangChar125TravelAbroadRoute,
    Char123LangChar125TravelCarRoute: Char123LangChar125TravelCarRoute,
    Char123LangChar125TravelOutdoorsRoute:
      Char123LangChar125TravelOutdoorsRoute,
    Char123LangChar125TravelIndexRoute: Char123LangChar125TravelIndexRoute,
  }

const Char123LangChar125TravelRouteWithChildren =
  Char123LangChar125TravelRoute._addFileChildren(
    Char123LangChar125TravelRouteChildren,
  )

interface Char123LangChar125RouteChildren {
  Char123LangChar125AboutRoute: typeof Char123LangChar125AboutRoute
  Char123LangChar125AccountRoute: typeof Char123LangChar125AccountRoute
  Char123LangChar125AuthRoute: typeof Char123LangChar125AuthRoute
  Char123LangChar125BestApartmentDogsRoute: typeof Char123LangChar125BestApartmentDogsRoute
  Char123LangChar125BestDogBreedsForFamiliesRoute: typeof Char123LangChar125BestDogBreedsForFamiliesRoute
  Char123LangChar125BestDogsForFirstTimeOwnersRoute: typeof Char123LangChar125BestDogsForFirstTimeOwnersRoute
  Char123LangChar125BrochureRoute: typeof Char123LangChar125BrochureRoute
  Char123LangChar125CompareRoute: typeof Char123LangChar125CompareRoute
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125DogLifeRoute: typeof Char123LangChar125DogLifeRoute
  Char123LangChar125DogsThatCanBeLeftAloneRoute: typeof Char123LangChar125DogsThatCanBeLeftAloneRoute
  Char123LangChar125FindMyDogRoute: typeof Char123LangChar125FindMyDogRoute
  Char123LangChar125GetADogRoute: typeof Char123LangChar125GetADogRouteWithChildren
  Char123LangChar125GuidesRoute: typeof Char123LangChar125GuidesRoute
  Char123LangChar125LowSheddingDogsRoute: typeof Char123LangChar125LowSheddingDogsRoute
  Char123LangChar125MemberCardRoute: typeof Char123LangChar125MemberCardRoute
  Char123LangChar125MostMismatchedBreedsRoute: typeof Char123LangChar125MostMismatchedBreedsRoute
  Char123LangChar125MyDogRoute: typeof Char123LangChar125MyDogRouteWithChildren
  Char123LangChar125PartnersRoute: typeof Char123LangChar125PartnersRouteWithChildren
  Char123LangChar125PlusRoute: typeof Char123LangChar125PlusRoute
  Char123LangChar125PrivacyRoute: typeof Char123LangChar125PrivacyRoute
  Char123LangChar125SourcesRoute: typeof Char123LangChar125SourcesRoute
  Char123LangChar125TermsRoute: typeof Char123LangChar125TermsRoute
  Char123LangChar125TrainRoute: typeof Char123LangChar125TrainRouteWithChildren
  Char123LangChar125TravelRoute: typeof Char123LangChar125TravelRouteWithChildren
  Char123LangChar125WhatADogCostsRoute: typeof Char123LangChar125WhatADogCostsRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125BreedsBreedIdRoute: typeof Char123LangChar125BreedsBreedIdRoute
  Char123LangChar125CanDogsEatFoodIdRoute: typeof Char123LangChar125CanDogsEatFoodIdRoute
  Char123LangChar125CheckoutCanceledRoute: typeof Char123LangChar125CheckoutCanceledRoute
  Char123LangChar125CheckoutSuccessRoute: typeof Char123LangChar125CheckoutSuccessRoute
  Char123LangChar125VerifyMemberIdRoute: typeof Char123LangChar125VerifyMemberIdRoute
  Char123LangChar125BreedsIndexRoute: typeof Char123LangChar125BreedsIndexRoute
  Char123LangChar125CanDogsEatIndexRoute: typeof Char123LangChar125CanDogsEatIndexRoute
}

const Char123LangChar125RouteChildren: Char123LangChar125RouteChildren = {
  Char123LangChar125AboutRoute: Char123LangChar125AboutRoute,
  Char123LangChar125AccountRoute: Char123LangChar125AccountRoute,
  Char123LangChar125AuthRoute: Char123LangChar125AuthRoute,
  Char123LangChar125BestApartmentDogsRoute:
    Char123LangChar125BestApartmentDogsRoute,
  Char123LangChar125BestDogBreedsForFamiliesRoute:
    Char123LangChar125BestDogBreedsForFamiliesRoute,
  Char123LangChar125BestDogsForFirstTimeOwnersRoute:
    Char123LangChar125BestDogsForFirstTimeOwnersRoute,
  Char123LangChar125BrochureRoute: Char123LangChar125BrochureRoute,
  Char123LangChar125CompareRoute: Char123LangChar125CompareRoute,
  Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
  Char123LangChar125DogLifeRoute: Char123LangChar125DogLifeRoute,
  Char123LangChar125DogsThatCanBeLeftAloneRoute:
    Char123LangChar125DogsThatCanBeLeftAloneRoute,
  Char123LangChar125FindMyDogRoute: Char123LangChar125FindMyDogRoute,
  Char123LangChar125GetADogRoute: Char123LangChar125GetADogRouteWithChildren,
  Char123LangChar125GuidesRoute: Char123LangChar125GuidesRoute,
  Char123LangChar125LowSheddingDogsRoute:
    Char123LangChar125LowSheddingDogsRoute,
  Char123LangChar125MemberCardRoute: Char123LangChar125MemberCardRoute,
  Char123LangChar125MostMismatchedBreedsRoute:
    Char123LangChar125MostMismatchedBreedsRoute,
  Char123LangChar125MyDogRoute: Char123LangChar125MyDogRouteWithChildren,
  Char123LangChar125PartnersRoute: Char123LangChar125PartnersRouteWithChildren,
  Char123LangChar125PlusRoute: Char123LangChar125PlusRoute,
  Char123LangChar125PrivacyRoute: Char123LangChar125PrivacyRoute,
  Char123LangChar125SourcesRoute: Char123LangChar125SourcesRoute,
  Char123LangChar125TermsRoute: Char123LangChar125TermsRoute,
  Char123LangChar125TrainRoute: Char123LangChar125TrainRouteWithChildren,
  Char123LangChar125TravelRoute: Char123LangChar125TravelRouteWithChildren,
  Char123LangChar125WhatADogCostsRoute: Char123LangChar125WhatADogCostsRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125BreedsBreedIdRoute: Char123LangChar125BreedsBreedIdRoute,
  Char123LangChar125CanDogsEatFoodIdRoute:
    Char123LangChar125CanDogsEatFoodIdRoute,
  Char123LangChar125CheckoutCanceledRoute:
    Char123LangChar125CheckoutCanceledRoute,
  Char123LangChar125CheckoutSuccessRoute:
    Char123LangChar125CheckoutSuccessRoute,
  Char123LangChar125VerifyMemberIdRoute: Char123LangChar125VerifyMemberIdRoute,
  Char123LangChar125BreedsIndexRoute: Char123LangChar125BreedsIndexRoute,
  Char123LangChar125CanDogsEatIndexRoute:
    Char123LangChar125CanDogsEatIndexRoute,
}

const Char123LangChar125RouteWithChildren =
  Char123LangChar125Route._addFileChildren(Char123LangChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LangChar125Route: Char123LangChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
