/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DogLifeRouteImport } from './routes/dog-life'
import { Route as FindMyDogRouteImport } from './routes/find-my-dog'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as TrainRouteImport } from './routes/train'
import { Route as BreedsIndexRouteImport } from './routes/breeds.index'
import { Route as BreedsBreedIdRouteImport } from './routes/breeds.$breedId'
import { Route as TrainIndexRouteImport } from './routes/train.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DogLifeRoute = DogLifeRouteImport.update({
  id: '/dog-life',
  path: '/dog-life',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyDogRoute = FindMyDogRouteImport.update({
  id: '/find-my-dog',
  path: '/find-my-dog',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsIndexRoute = BreedsIndexRouteImport.update({
  id: '/breeds/',
  path: '/breeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsBreedIdRoute = BreedsBreedIdRouteImport.update({
  id: '/breeds/$breedId',
  path: '/breeds/$breedId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/guides': typeof GuidesRoute
  '/train': typeof TrainRouteWithChildren
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/breeds/': typeof BreedsIndexRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/guides': typeof GuidesRoute
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/breeds': typeof BreedsIndexRoute
  '/train': typeof TrainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/guides': typeof GuidesRoute
  '/train': typeof TrainRouteWithChildren
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/breeds/': typeof BreedsIndexRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/dog-life'
    | '/find-my-dog'
    | '/guides'
    | '/train'
    | '/breeds/$breedId'
    | '/breeds/'
    | '/train/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/dog-life'
    | '/find-my-dog'
    | '/guides'
    | '/breeds/$breedId'
    | '/breeds'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/dog-life'
    | '/find-my-dog'
    | '/guides'
    | '/train'
    | '/breeds/$breedId'
    | '/breeds/'
    | '/train/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  DogLifeRoute: typeof DogLifeRoute
  FindMyDogRoute: typeof FindMyDogRoute
  GuidesRoute: typeof GuidesRoute
  TrainRoute: typeof TrainRouteWithChildren
  BreedsBreedIdRoute: typeof BreedsBreedIdRoute
  BreedsIndexRoute: typeof BreedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog-life': {
      id: '/dog-life'
      path: '/dog-life'
      fullPath: '/dog-life'
      preLoaderRoute: typeof DogLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-dog': {
      id: '/find-my-dog'
      path: '/find-my-dog'
      fullPath: '/find-my-dog'
      preLoaderRoute: typeof FindMyDogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/': {
      id: '/breeds/'
      path: '/breeds'
      fullPath: '/breeds/'
      preLoaderRoute: typeof BreedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/$breedId': {
      id: '/breeds/$breedId'
      path: '/breeds/$breedId'
      fullPath: '/breeds/$breedId'
      preLoaderRoute: typeof BreedsBreedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/': {
      id: '/train/'
      path: '/'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof TrainRoute
    }
  }
}

interface TrainRouteChildren {
  TrainIndexRoute: typeof TrainIndexRoute
}

const TrainRouteChildren: TrainRouteChildren = {
  TrainIndexRoute: TrainIndexRoute,
}

const TrainRouteWithChildren = TrainRoute._addFileChildren(TrainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  DogLifeRoute: DogLifeRoute,
  FindMyDogRoute: FindMyDogRoute,
  GuidesRoute: GuidesRoute,
  TrainRoute: TrainRouteWithChildren,
  BreedsBreedIdRoute: BreedsBreedIdRoute,
  BreedsIndexRoute: BreedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
