/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DogLifeRouteImport } from './routes/dog-life'
import { Route as FindMyDogRouteImport } from './routes/find-my-dog'
import { Route as GetADogRouteImport } from './routes/get-a-dog'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as MyDogRouteImport } from './routes/my-dog'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as BreedsIndexRouteImport } from './routes/breeds.index'
import { Route as BreedsBreedIdRouteImport } from './routes/breeds.$breedId'
import { Route as GetADogIndexRouteImport } from './routes/get-a-dog.index'
import { Route as GetADogChooseRouteImport } from './routes/get-a-dog.choose'
import { Route as GetADogCostsRouteImport } from './routes/get-a-dog.costs'
import { Route as GetADogPrepareRouteImport } from './routes/get-a-dog.prepare'
import { Route as GetADogReadyRouteImport } from './routes/get-a-dog.ready'
import { Route as GetADogWelcomeHomeRouteImport } from './routes/get-a-dog.welcome-home'
import { Route as MyDogIndexRouteImport } from './routes/my-dog.index'
import { Route as MyDogContactsRouteImport } from './routes/my-dog.contacts'
import { Route as MyDogFoodRouteImport } from './routes/my-dog.food'
import { Route as MyDogNutritionRouteImport } from './routes/my-dog.nutrition'
import { Route as MyDogPackRouteImport } from './routes/my-dog.pack'
import { Route as MyDogPrintRouteImport } from './routes/my-dog.print'
import { Route as MyDogSetupRouteImport } from './routes/my-dog.setup'
import { Route as MyDogVetRouteImport } from './routes/my-dog.vet'
import { Route as MyDogWeekRouteImport } from './routes/my-dog.week'
import { Route as MyDogWeightRouteImport } from './routes/my-dog.weight'
import { Route as TrainIndexRouteImport } from './routes/train.index'
import { Route as TrainJourneyRouteImport } from './routes/train.journey'
import { Route as TrainLibraryRouteImport } from './routes/train.library'
import { Route as TrainSetupRouteImport } from './routes/train.setup'
import { Route as TravelIndexRouteImport } from './routes/travel.index'
import { Route as TravelAbroadRouteImport } from './routes/travel.abroad'
import { Route as TravelCarRouteImport } from './routes/travel.car'
import { Route as TravelOutdoorsRouteImport } from './routes/travel.outdoors'
import { Route as GetADogBreedBreedIdRouteImport } from './routes/get-a-dog.breed.$breedId'
import { Route as MyDogCareTopicIdRouteImport } from './routes/my-dog.care.$topicId'
import { Route as TrainLessonsLessonIdRouteImport } from './routes/train.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DogLifeRoute = DogLifeRouteImport.update({
  id: '/dog-life',
  path: '/dog-life',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyDogRoute = FindMyDogRouteImport.update({
  id: '/find-my-dog',
  path: '/find-my-dog',
  getParentRoute: () => rootRouteImport,
} as any)
const GetADogRoute = GetADogRouteImport.update({
  id: '/get-a-dog',
  path: '/get-a-dog',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDogRoute = MyDogRouteImport.update({
  id: '/my-dog',
  path: '/my-dog',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsIndexRoute = BreedsIndexRouteImport.update({
  id: '/breeds/',
  path: '/breeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsBreedIdRoute = BreedsBreedIdRouteImport.update({
  id: '/breeds/$breedId',
  path: '/breeds/$breedId',
  getParentRoute: () => rootRouteImport,
} as any)
const GetADogIndexRoute = GetADogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GetADogRoute,
} as any)
const GetADogChooseRoute = GetADogChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => GetADogRoute,
} as any)
const GetADogCostsRoute = GetADogCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => GetADogRoute,
} as any)
const GetADogPrepareRoute = GetADogPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => GetADogRoute,
} as any)
const GetADogReadyRoute = GetADogReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => GetADogRoute,
} as any)
const GetADogWelcomeHomeRoute = GetADogWelcomeHomeRouteImport.update({
  id: '/welcome-home',
  path: '/welcome-home',
  getParentRoute: () => GetADogRoute,
} as any)
const MyDogIndexRoute = MyDogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogContactsRoute = MyDogContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogFoodRoute = MyDogFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogNutritionRoute = MyDogNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogPackRoute = MyDogPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogPrintRoute = MyDogPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogSetupRoute = MyDogSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogVetRoute = MyDogVetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogWeekRoute = MyDogWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => MyDogRoute,
} as any)
const MyDogWeightRoute = MyDogWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => MyDogRoute,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainRoute,
} as any)
const TrainJourneyRoute = TrainJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => TrainRoute,
} as any)
const TrainLibraryRoute = TrainLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => TrainRoute,
} as any)
const TrainSetupRoute = TrainSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => TrainRoute,
} as any)
const TravelIndexRoute = TravelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TravelRoute,
} as any)
const TravelAbroadRoute = TravelAbroadRouteImport.update({
  id: '/abroad',
  path: '/abroad',
  getParentRoute: () => TravelRoute,
} as any)
const TravelCarRoute = TravelCarRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => TravelRoute,
} as any)
const TravelOutdoorsRoute = TravelOutdoorsRouteImport.update({
  id: '/outdoors',
  path: '/outdoors',
  getParentRoute: () => TravelRoute,
} as any)
const GetADogBreedBreedIdRoute = GetADogBreedBreedIdRouteImport.update({
  id: '/breed/$breedId',
  path: '/breed/$breedId',
  getParentRoute: () => GetADogRoute,
} as any)
const MyDogCareTopicIdRoute = MyDogCareTopicIdRouteImport.update({
  id: '/care/$topicId',
  path: '/care/$topicId',
  getParentRoute: () => MyDogRoute,
} as any)
const TrainLessonsLessonIdRoute = TrainLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => TrainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/get-a-dog': typeof GetADogRouteWithChildren
  '/guides': typeof GuidesRoute
  '/my-dog': typeof MyDogRouteWithChildren
  '/plus': typeof PlusRoute
  '/train': typeof TrainRouteWithChildren
  '/travel': typeof TravelRouteWithChildren
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/get-a-dog/choose': typeof GetADogChooseRoute
  '/get-a-dog/costs': typeof GetADogCostsRoute
  '/get-a-dog/prepare': typeof GetADogPrepareRoute
  '/get-a-dog/ready': typeof GetADogReadyRoute
  '/get-a-dog/welcome-home': typeof GetADogWelcomeHomeRoute
  '/my-dog/contacts': typeof MyDogContactsRoute
  '/my-dog/food': typeof MyDogFoodRoute
  '/my-dog/nutrition': typeof MyDogNutritionRoute
  '/my-dog/pack': typeof MyDogPackRoute
  '/my-dog/print': typeof MyDogPrintRoute
  '/my-dog/setup': typeof MyDogSetupRoute
  '/my-dog/vet': typeof MyDogVetRoute
  '/my-dog/week': typeof MyDogWeekRoute
  '/my-dog/weight': typeof MyDogWeightRoute
  '/train/journey': typeof TrainJourneyRoute
  '/train/library': typeof TrainLibraryRoute
  '/train/setup': typeof TrainSetupRoute
  '/travel/abroad': typeof TravelAbroadRoute
  '/travel/car': typeof TravelCarRoute
  '/travel/outdoors': typeof TravelOutdoorsRoute
  '/breeds/': typeof BreedsIndexRoute
  '/get-a-dog/': typeof GetADogIndexRoute
  '/my-dog/': typeof MyDogIndexRoute
  '/train/': typeof TrainIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/get-a-dog/breed/$breedId': typeof GetADogBreedBreedIdRoute
  '/my-dog/care/$topicId': typeof MyDogCareTopicIdRoute
  '/train/lessons/$lessonId': typeof TrainLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/guides': typeof GuidesRoute
  '/plus': typeof PlusRoute
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/get-a-dog/choose': typeof GetADogChooseRoute
  '/get-a-dog/costs': typeof GetADogCostsRoute
  '/get-a-dog/prepare': typeof GetADogPrepareRoute
  '/get-a-dog/ready': typeof GetADogReadyRoute
  '/get-a-dog/welcome-home': typeof GetADogWelcomeHomeRoute
  '/my-dog/contacts': typeof MyDogContactsRoute
  '/my-dog/food': typeof MyDogFoodRoute
  '/my-dog/nutrition': typeof MyDogNutritionRoute
  '/my-dog/pack': typeof MyDogPackRoute
  '/my-dog/print': typeof MyDogPrintRoute
  '/my-dog/setup': typeof MyDogSetupRoute
  '/my-dog/vet': typeof MyDogVetRoute
  '/my-dog/week': typeof MyDogWeekRoute
  '/my-dog/weight': typeof MyDogWeightRoute
  '/train/journey': typeof TrainJourneyRoute
  '/train/library': typeof TrainLibraryRoute
  '/train/setup': typeof TrainSetupRoute
  '/travel/abroad': typeof TravelAbroadRoute
  '/travel/car': typeof TravelCarRoute
  '/travel/outdoors': typeof TravelOutdoorsRoute
  '/breeds': typeof BreedsIndexRoute
  '/get-a-dog': typeof GetADogIndexRoute
  '/my-dog': typeof MyDogIndexRoute
  '/train': typeof TrainIndexRoute
  '/travel': typeof TravelIndexRoute
  '/get-a-dog/breed/$breedId': typeof GetADogBreedBreedIdRoute
  '/my-dog/care/$topicId': typeof MyDogCareTopicIdRoute
  '/train/lessons/$lessonId': typeof TrainLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dog-life': typeof DogLifeRoute
  '/find-my-dog': typeof FindMyDogRoute
  '/get-a-dog': typeof GetADogRouteWithChildren
  '/guides': typeof GuidesRoute
  '/my-dog': typeof MyDogRouteWithChildren
  '/plus': typeof PlusRoute
  '/train': typeof TrainRouteWithChildren
  '/travel': typeof TravelRouteWithChildren
  '/breeds/$breedId': typeof BreedsBreedIdRoute
  '/get-a-dog/choose': typeof GetADogChooseRoute
  '/get-a-dog/costs': typeof GetADogCostsRoute
  '/get-a-dog/prepare': typeof GetADogPrepareRoute
  '/get-a-dog/ready': typeof GetADogReadyRoute
  '/get-a-dog/welcome-home': typeof GetADogWelcomeHomeRoute
  '/my-dog/contacts': typeof MyDogContactsRoute
  '/my-dog/food': typeof MyDogFoodRoute
  '/my-dog/nutrition': typeof MyDogNutritionRoute
  '/my-dog/pack': typeof MyDogPackRoute
  '/my-dog/print': typeof MyDogPrintRoute
  '/my-dog/setup': typeof MyDogSetupRoute
  '/my-dog/vet': typeof MyDogVetRoute
  '/my-dog/week': typeof MyDogWeekRoute
  '/my-dog/weight': typeof MyDogWeightRoute
  '/train/journey': typeof TrainJourneyRoute
  '/train/library': typeof TrainLibraryRoute
  '/train/setup': typeof TrainSetupRoute
  '/travel/abroad': typeof TravelAbroadRoute
  '/travel/car': typeof TravelCarRoute
  '/travel/outdoors': typeof TravelOutdoorsRoute
  '/breeds/': typeof BreedsIndexRoute
  '/get-a-dog/': typeof GetADogIndexRoute
  '/my-dog/': typeof MyDogIndexRoute
  '/train/': typeof TrainIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/get-a-dog/breed/$breedId': typeof GetADogBreedBreedIdRoute
  '/my-dog/care/$topicId': typeof MyDogCareTopicIdRoute
  '/train/lessons/$lessonId': typeof TrainLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/dog-life'
    | '/find-my-dog'
    | '/get-a-dog'
    | '/guides'
    | '/my-dog'
    | '/plus'
    | '/train'
    | '/travel'
    | '/breeds/$breedId'
    | '/get-a-dog/choose'
    | '/get-a-dog/costs'
    | '/get-a-dog/prepare'
    | '/get-a-dog/ready'
    | '/get-a-dog/welcome-home'
    | '/my-dog/contacts'
    | '/my-dog/food'
    | '/my-dog/nutrition'
    | '/my-dog/pack'
    | '/my-dog/print'
    | '/my-dog/setup'
    | '/my-dog/vet'
    | '/my-dog/week'
    | '/my-dog/weight'
    | '/train/journey'
    | '/train/library'
    | '/train/setup'
    | '/travel/abroad'
    | '/travel/car'
    | '/travel/outdoors'
    | '/breeds/'
    | '/get-a-dog/'
    | '/my-dog/'
    | '/train/'
    | '/travel/'
    | '/get-a-dog/breed/$breedId'
    | '/my-dog/care/$topicId'
    | '/train/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/dog-life'
    | '/find-my-dog'
    | '/guides'
    | '/plus'
    | '/breeds/$breedId'
    | '/get-a-dog/choose'
    | '/get-a-dog/costs'
    | '/get-a-dog/prepare'
    | '/get-a-dog/ready'
    | '/get-a-dog/welcome-home'
    | '/my-dog/contacts'
    | '/my-dog/food'
    | '/my-dog/nutrition'
    | '/my-dog/pack'
    | '/my-dog/print'
    | '/my-dog/setup'
    | '/my-dog/vet'
    | '/my-dog/week'
    | '/my-dog/weight'
    | '/train/journey'
    | '/train/library'
    | '/train/setup'
    | '/travel/abroad'
    | '/travel/car'
    | '/travel/outdoors'
    | '/breeds'
    | '/get-a-dog'
    | '/my-dog'
    | '/train'
    | '/travel'
    | '/get-a-dog/breed/$breedId'
    | '/my-dog/care/$topicId'
    | '/train/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/dog-life'
    | '/find-my-dog'
    | '/get-a-dog'
    | '/guides'
    | '/my-dog'
    | '/plus'
    | '/train'
    | '/travel'
    | '/breeds/$breedId'
    | '/get-a-dog/choose'
    | '/get-a-dog/costs'
    | '/get-a-dog/prepare'
    | '/get-a-dog/ready'
    | '/get-a-dog/welcome-home'
    | '/my-dog/contacts'
    | '/my-dog/food'
    | '/my-dog/nutrition'
    | '/my-dog/pack'
    | '/my-dog/print'
    | '/my-dog/setup'
    | '/my-dog/vet'
    | '/my-dog/week'
    | '/my-dog/weight'
    | '/train/journey'
    | '/train/library'
    | '/train/setup'
    | '/travel/abroad'
    | '/travel/car'
    | '/travel/outdoors'
    | '/breeds/'
    | '/get-a-dog/'
    | '/my-dog/'
    | '/train/'
    | '/travel/'
    | '/get-a-dog/breed/$breedId'
    | '/my-dog/care/$topicId'
    | '/train/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DogLifeRoute: typeof DogLifeRoute
  FindMyDogRoute: typeof FindMyDogRoute
  GetADogRoute: typeof GetADogRouteWithChildren
  GuidesRoute: typeof GuidesRoute
  MyDogRoute: typeof MyDogRouteWithChildren
  PlusRoute: typeof PlusRoute
  TrainRoute: typeof TrainRouteWithChildren
  TravelRoute: typeof TravelRouteWithChildren
  BreedsBreedIdRoute: typeof BreedsBreedIdRoute
  BreedsIndexRoute: typeof BreedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog-life': {
      id: '/dog-life'
      path: '/dog-life'
      fullPath: '/dog-life'
      preLoaderRoute: typeof DogLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-dog': {
      id: '/find-my-dog'
      path: '/find-my-dog'
      fullPath: '/find-my-dog'
      preLoaderRoute: typeof FindMyDogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-dog': {
      id: '/get-a-dog'
      path: '/get-a-dog'
      fullPath: '/get-a-dog'
      preLoaderRoute: typeof GetADogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-dog': {
      id: '/my-dog'
      path: '/my-dog'
      fullPath: '/my-dog'
      preLoaderRoute: typeof MyDogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/': {
      id: '/breeds/'
      path: '/breeds'
      fullPath: '/breeds/'
      preLoaderRoute: typeof BreedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/$breedId': {
      id: '/breeds/$breedId'
      path: '/breeds/$breedId'
      fullPath: '/breeds/$breedId'
      preLoaderRoute: typeof BreedsBreedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-dog/': {
      id: '/get-a-dog/'
      path: '/'
      fullPath: '/get-a-dog/'
      preLoaderRoute: typeof GetADogIndexRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/get-a-dog/choose': {
      id: '/get-a-dog/choose'
      path: '/choose'
      fullPath: '/get-a-dog/choose'
      preLoaderRoute: typeof GetADogChooseRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/get-a-dog/costs': {
      id: '/get-a-dog/costs'
      path: '/costs'
      fullPath: '/get-a-dog/costs'
      preLoaderRoute: typeof GetADogCostsRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/get-a-dog/prepare': {
      id: '/get-a-dog/prepare'
      path: '/prepare'
      fullPath: '/get-a-dog/prepare'
      preLoaderRoute: typeof GetADogPrepareRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/get-a-dog/ready': {
      id: '/get-a-dog/ready'
      path: '/ready'
      fullPath: '/get-a-dog/ready'
      preLoaderRoute: typeof GetADogReadyRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/get-a-dog/welcome-home': {
      id: '/get-a-dog/welcome-home'
      path: '/welcome-home'
      fullPath: '/get-a-dog/welcome-home'
      preLoaderRoute: typeof GetADogWelcomeHomeRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/my-dog/': {
      id: '/my-dog/'
      path: '/'
      fullPath: '/my-dog/'
      preLoaderRoute: typeof MyDogIndexRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/contacts': {
      id: '/my-dog/contacts'
      path: '/contacts'
      fullPath: '/my-dog/contacts'
      preLoaderRoute: typeof MyDogContactsRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/food': {
      id: '/my-dog/food'
      path: '/food'
      fullPath: '/my-dog/food'
      preLoaderRoute: typeof MyDogFoodRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/nutrition': {
      id: '/my-dog/nutrition'
      path: '/nutrition'
      fullPath: '/my-dog/nutrition'
      preLoaderRoute: typeof MyDogNutritionRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/pack': {
      id: '/my-dog/pack'
      path: '/pack'
      fullPath: '/my-dog/pack'
      preLoaderRoute: typeof MyDogPackRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/print': {
      id: '/my-dog/print'
      path: '/print'
      fullPath: '/my-dog/print'
      preLoaderRoute: typeof MyDogPrintRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/setup': {
      id: '/my-dog/setup'
      path: '/setup'
      fullPath: '/my-dog/setup'
      preLoaderRoute: typeof MyDogSetupRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/vet': {
      id: '/my-dog/vet'
      path: '/vet'
      fullPath: '/my-dog/vet'
      preLoaderRoute: typeof MyDogVetRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/week': {
      id: '/my-dog/week'
      path: '/week'
      fullPath: '/my-dog/week'
      preLoaderRoute: typeof MyDogWeekRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/my-dog/weight': {
      id: '/my-dog/weight'
      path: '/weight'
      fullPath: '/my-dog/weight'
      preLoaderRoute: typeof MyDogWeightRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/train/': {
      id: '/train/'
      path: '/'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof TrainRoute
    }
    '/train/journey': {
      id: '/train/journey'
      path: '/journey'
      fullPath: '/train/journey'
      preLoaderRoute: typeof TrainJourneyRouteImport
      parentRoute: typeof TrainRoute
    }
    '/train/library': {
      id: '/train/library'
      path: '/library'
      fullPath: '/train/library'
      preLoaderRoute: typeof TrainLibraryRouteImport
      parentRoute: typeof TrainRoute
    }
    '/train/setup': {
      id: '/train/setup'
      path: '/setup'
      fullPath: '/train/setup'
      preLoaderRoute: typeof TrainSetupRouteImport
      parentRoute: typeof TrainRoute
    }
    '/travel/': {
      id: '/travel/'
      path: '/'
      fullPath: '/travel/'
      preLoaderRoute: typeof TravelIndexRouteImport
      parentRoute: typeof TravelRoute
    }
    '/travel/abroad': {
      id: '/travel/abroad'
      path: '/abroad'
      fullPath: '/travel/abroad'
      preLoaderRoute: typeof TravelAbroadRouteImport
      parentRoute: typeof TravelRoute
    }
    '/travel/car': {
      id: '/travel/car'
      path: '/car'
      fullPath: '/travel/car'
      preLoaderRoute: typeof TravelCarRouteImport
      parentRoute: typeof TravelRoute
    }
    '/travel/outdoors': {
      id: '/travel/outdoors'
      path: '/outdoors'
      fullPath: '/travel/outdoors'
      preLoaderRoute: typeof TravelOutdoorsRouteImport
      parentRoute: typeof TravelRoute
    }
    '/get-a-dog/breed/$breedId': {
      id: '/get-a-dog/breed/$breedId'
      path: '/breed/$breedId'
      fullPath: '/get-a-dog/breed/$breedId'
      preLoaderRoute: typeof GetADogBreedBreedIdRouteImport
      parentRoute: typeof GetADogRoute
    }
    '/my-dog/care/$topicId': {
      id: '/my-dog/care/$topicId'
      path: '/care/$topicId'
      fullPath: '/my-dog/care/$topicId'
      preLoaderRoute: typeof MyDogCareTopicIdRouteImport
      parentRoute: typeof MyDogRoute
    }
    '/train/lessons/$lessonId': {
      id: '/train/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/train/lessons/$lessonId'
      preLoaderRoute: typeof TrainLessonsLessonIdRouteImport
      parentRoute: typeof TrainRoute
    }
  }
}

interface GetADogRouteChildren {
  GetADogChooseRoute: typeof GetADogChooseRoute
  GetADogCostsRoute: typeof GetADogCostsRoute
  GetADogPrepareRoute: typeof GetADogPrepareRoute
  GetADogReadyRoute: typeof GetADogReadyRoute
  GetADogWelcomeHomeRoute: typeof GetADogWelcomeHomeRoute
  GetADogIndexRoute: typeof GetADogIndexRoute
  GetADogBreedBreedIdRoute: typeof GetADogBreedBreedIdRoute
}

const GetADogRouteChildren: GetADogRouteChildren = {
  GetADogChooseRoute: GetADogChooseRoute,
  GetADogCostsRoute: GetADogCostsRoute,
  GetADogPrepareRoute: GetADogPrepareRoute,
  GetADogReadyRoute: GetADogReadyRoute,
  GetADogWelcomeHomeRoute: GetADogWelcomeHomeRoute,
  GetADogIndexRoute: GetADogIndexRoute,
  GetADogBreedBreedIdRoute: GetADogBreedBreedIdRoute,
}

const GetADogRouteWithChildren =
  GetADogRoute._addFileChildren(GetADogRouteChildren)

interface MyDogRouteChildren {
  MyDogContactsRoute: typeof MyDogContactsRoute
  MyDogFoodRoute: typeof MyDogFoodRoute
  MyDogNutritionRoute: typeof MyDogNutritionRoute
  MyDogPackRoute: typeof MyDogPackRoute
  MyDogPrintRoute: typeof MyDogPrintRoute
  MyDogSetupRoute: typeof MyDogSetupRoute
  MyDogVetRoute: typeof MyDogVetRoute
  MyDogWeekRoute: typeof MyDogWeekRoute
  MyDogWeightRoute: typeof MyDogWeightRoute
  MyDogIndexRoute: typeof MyDogIndexRoute
  MyDogCareTopicIdRoute: typeof MyDogCareTopicIdRoute
}

const MyDogRouteChildren: MyDogRouteChildren = {
  MyDogContactsRoute: MyDogContactsRoute,
  MyDogFoodRoute: MyDogFoodRoute,
  MyDogNutritionRoute: MyDogNutritionRoute,
  MyDogPackRoute: MyDogPackRoute,
  MyDogPrintRoute: MyDogPrintRoute,
  MyDogSetupRoute: MyDogSetupRoute,
  MyDogVetRoute: MyDogVetRoute,
  MyDogWeekRoute: MyDogWeekRoute,
  MyDogWeightRoute: MyDogWeightRoute,
  MyDogIndexRoute: MyDogIndexRoute,
  MyDogCareTopicIdRoute: MyDogCareTopicIdRoute,
}

const MyDogRouteWithChildren = MyDogRoute._addFileChildren(MyDogRouteChildren)

interface TrainRouteChildren {
  TrainJourneyRoute: typeof TrainJourneyRoute
  TrainLibraryRoute: typeof TrainLibraryRoute
  TrainSetupRoute: typeof TrainSetupRoute
  TrainIndexRoute: typeof TrainIndexRoute
  TrainLessonsLessonIdRoute: typeof TrainLessonsLessonIdRoute
}

const TrainRouteChildren: TrainRouteChildren = {
  TrainJourneyRoute: TrainJourneyRoute,
  TrainLibraryRoute: TrainLibraryRoute,
  TrainSetupRoute: TrainSetupRoute,
  TrainIndexRoute: TrainIndexRoute,
  TrainLessonsLessonIdRoute: TrainLessonsLessonIdRoute,
}

const TrainRouteWithChildren = TrainRoute._addFileChildren(TrainRouteChildren)

interface TravelRouteChildren {
  TravelAbroadRoute: typeof TravelAbroadRoute
  TravelCarRoute: typeof TravelCarRoute
  TravelOutdoorsRoute: typeof TravelOutdoorsRoute
  TravelIndexRoute: typeof TravelIndexRoute
}

const TravelRouteChildren: TravelRouteChildren = {
  TravelAbroadRoute: TravelAbroadRoute,
  TravelCarRoute: TravelCarRoute,
  TravelOutdoorsRoute: TravelOutdoorsRoute,
  TravelIndexRoute: TravelIndexRoute,
}

const TravelRouteWithChildren =
  TravelRoute._addFileChildren(TravelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DogLifeRoute: DogLifeRoute,
  FindMyDogRoute: FindMyDogRoute,
  GetADogRoute: GetADogRouteWithChildren,
  GuidesRoute: GuidesRoute,
  MyDogRoute: MyDogRouteWithChildren,
  PlusRoute: PlusRoute,
  TrainRoute: TrainRouteWithChildren,
  TravelRoute: TravelRouteWithChildren,
  BreedsBreedIdRoute: BreedsBreedIdRoute,
  BreedsIndexRoute: BreedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
